// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// stringEncoder.hh
//

#ifndef LZZ_stringEncoder_hh
#define LZZ_stringEncoder_hh
#define LZZ_INLINE inline
namespace sttSav
{
  class StringEncoder
  {
  public:
    STTSAV_STRING & buff;
    StringEncoder (STTSAV_STRING & storage);
    void reserve (uint32_t const initialCapacity);
    uint64_t getSeek () const;
    template <typename T>
    void parse (T const & t);
    template <typename T>
    void parseAt (uint64_t const offset, T const & value);
    void parseSize (uint64_t const trueSize);
    void parseString (STTSAV_STRING const & str);
    void parseString (char const * str, uint32_t const sz);
  };
}
namespace sttSav
{
  class StringDecoder
  {
  public:
    STTSAV_STRING const & buff;
    uint64_t seek;
    bool hasError;
    StringDecoder (STTSAV_STRING const & _src);
    bool isOk () const;
    void onBufferOverflow (uint64_t const read);
    bool checkError2 (uint64_t const read);
    template <typename T>
    void parse (T & tout);
    template <typename T>
    T parse ();
    template <typename T>
    void parseAt (uint64_t offset, T & tout) const;
    void parseString (STTSAV_STRING & out);
    uint64_t parseSize ();
  };
}
namespace sttSav
{
  LZZ_INLINE StringEncoder::StringEncoder (STTSAV_STRING & storage)
    : buff (storage)
                                                                     {}
}
namespace sttSav
{
  LZZ_INLINE void StringEncoder::reserve (uint32_t const initialCapacity)
                                                            {
		buff.reserve(initialCapacity);
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t StringEncoder::getSeek () const
                                        { return buff.size(); }
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringEncoder::parse (T const & t)
                                       {
		buff += std::string_view((char*)&t, sizeof(T));
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringEncoder::parseAt (uint64_t const offset, T const & value)
                                                                   {
		memcpy(&buff[offset], &value, sizeof(T));
		}
}
namespace sttSav
{
  LZZ_INLINE void StringEncoder::parseSize (uint64_t const trueSize)
                                                       {
		if (trueSize >= uint8_t(-1)) {
			parse<uint8_t>(-1);
			parse<uint64_t>(trueSize);
			}
		else
			parse<uint8_t>(trueSize);
		}
}
namespace sttSav
{
  LZZ_INLINE StringDecoder::StringDecoder (STTSAV_STRING const & _src)
    : buff (_src), seek (0), hasError (false)
                                                                                                {}
}
namespace sttSav
{
  LZZ_INLINE bool StringDecoder::isOk () const
                                 { return !hasError; }
}
namespace sttSav
{
  LZZ_INLINE bool StringDecoder::checkError2 (uint64_t const read)
                                                     {
		if (hasError) return true;
		if (read + seek > buff.size()) {
			onBufferOverflow(read);
			hasError = true;
			}
		return hasError;
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringDecoder::parse (T & tout)
                                    {
		if (checkError2(sizeof(T))) return;
		buff.copy((char *) &tout, sizeof(T), seek);
		seek += sizeof(T);
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE T StringDecoder::parse ()
                         {
		if (checkError2(sizeof(T))) return T();
		T tout;
		buff.copy((char *) &tout, sizeof(T), seek);
		seek += sizeof(T);
		return tout;
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringDecoder::parseAt (uint64_t offset, T & tout) const
                                                            {
		buff.copy((char *) &tout, sizeof(T), offset);
		}
}
namespace sttSav
{
  LZZ_INLINE void StringDecoder::parseString (STTSAV_STRING & out)
                                                    {
		uint64_t sz = parseSize();
		seek += sz;
		out = buff.substr(seek-sz, sz);
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t StringDecoder::parseSize ()
                                    {
		uint64_t sz = parse<uint8_t>();
		if (sz == uint8_t(-1))
			sz = parse<uint64_t>();
		return sz;
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#define STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#define LZZ_OVERRIDE
// stringEncoder.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  void StringEncoder::parseString (STTSAV_STRING const & str)
                                                    {
		parseSize(str.size());
		buff += str;
		}
}
namespace sttSav
{
  void StringEncoder::parseString (char const * str, uint32_t const sz)
                                                             {
		parseSize(sz);
		buff += str;
		}
}
namespace sttSav
{
  void StringDecoder::onBufferOverflow (uint64_t const read)
                                                   {
		printf("stt-sav buffer overflow! read %i at %i of string size %i\n", (int)read, (int)seek, (int)buff.size());
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// binaryValueWriter.hh
//

#ifndef LZZ_binaryValueWriter_hh
#define LZZ_binaryValueWriter_hh
namespace sttSav {
struct bvConstants {
	static constexpr uint8_t BV_EMPTY = 0;
	static constexpr uint8_t BV_BOOL = 1;
static constexpr uint8_t BV_NUMBERS_START = 2;
	static constexpr uint8_t BV_FLOAT = 2;
	static constexpr uint8_t BV_DOUBLE = 3;
	static constexpr uint8_t BV_UINT8 = 4;
	static constexpr uint8_t BV_UINT16 = 5;
	static constexpr uint8_t BV_UINT32 = 6;
	static constexpr uint8_t BV_UINT64 = 7;
	static constexpr uint8_t BV_INT8 = 8;
	static constexpr uint8_t BV_INT16 = 9;
	static constexpr uint8_t BV_INT32 = 10;
	static constexpr uint8_t BV_INT64 = 11;
static constexpr uint8_t BV_NUMBERS_END = 11;
	static constexpr uint8_t BV_STRING = 12;
	static constexpr uint8_t BV_OBJECT = 13;
	static constexpr uint8_t BV_ARRAY = 14;
	};
}
#define LZZ_INLINE inline
namespace sttSav
{
  class BinaryValue
  {
  public:
    StringDecoder * dec;
    uint64_t offset;
  public:
    BinaryValue ();
    BinaryValue (StringDecoder * _dec);
  protected:
    uint8_t getBvType () const;
    uint64_t payloadOffset () const;
    uint32_t getJumpSize () const;
    uint32_t getMemberCount () const;
    uint64_t childOffset () const;
  public:
    uint64_t nextOffset () const;
  protected:
    int64_t getInteger () const;
    double getFloating () const;
  public:
    bool IsValid () const;
    bool IsArray () const;
    bool IsObject () const;
    bool IsString () const;
    bool IsBool () const;
    bool IsNumber () const;
    bool IsSignedInteger () const;
    bool IsUnsignedInteger () const;
    bool IsFloating () const;
    uint32_t Size () const;
    int8_t GetInt8 () const;
    int16_t GetInt16 () const;
    int32_t GetInt32 () const;
    int64_t GetInt64 () const;
    int32_t GetInt () const;
    uint8_t GetUint8 () const;
    uint16_t GetUint16 () const;
    uint32_t GetUint32 () const;
    uint64_t GetUint64 () const;
    uint32_t GetUint () const;
    float GetFloat () const;
    float GetDouble () const;
    bool GetBool () const;
    STTSAV_STRING GetString () const;
    void GetStringRef (STTSAV_STRING & out) const;
    uint32_t GetStringLength () const;
    BinaryValue operator [] (uint32_t index) const;
  protected:
    void findChildByKey (char const * key, uint32_t & idxOut, uint64_t & offsetOut) const;
  public:
    BinaryValue operator [] (char const * key) const;
    void ExtractMembers (BinaryValue * bvOut, STTSAV_STRING * keysOut) const;
    void ExtractArrayElements (BinaryValue * bvOut) const;
    bool HasMember (char const * key) const;
    STTSAV_STRING toDbgString () const;
    STTSAV_STRING toDbgPrintableString (uint32_t const indent) const;
    STTSAV_STRING toDbgStringIndented (uint32_t indent) const;
  };
}
namespace sttSav
{
  class BinaryWriter
  {
  public:
    StringEncoder * enc;
  protected:
    struct scope
    {
      uint64_t startOffset;
      uint32_t memberCount;
      bool isObject;
    };
    STTSAV_VECTOR <scope> stack;
  public:
    BinaryWriter ();
    BinaryWriter (StringEncoder * _enc);
  protected:
    void onValueWritten ();
    void startContainer (uint8_t const bvType, bool const isObject);
    void endContainer ();
    template <typename T>
    void writePrimitive (uint8_t const bvType, T const value);
  public:
    void StartObject ();
    void StartArray ();
    void EndObject ();
    void EndArray ();
    void Key (char const * str, uint32_t const sz);
    void Key (char const * str);
    void Int (int const v);
    void Int8 (int8_t const v);
    void Int16 (int16_t const v);
    void Int32 (int32_t const v);
    void Int64 (int64_t const v);
    void Uint (unsigned int const v);
    void Uint8 (uint8_t const v);
    void Uint16 (uint16_t const v);
    void Uint32 (uint32_t const v);
    void Uint64 (uint64_t const v);
    void Float (float const v);
    void Double (double const v);
    void Bool (bool const v);
    void String (char const * str, uint32_t const len);
    void String (char const * str);
    void String (STTSAV_STRING const & str);
  };
}
namespace sttSav
{
  LZZ_INLINE BinaryValue::BinaryValue ()
    : dec (NULL), offset (0)
                                                {}
}
namespace sttSav
{
  LZZ_INLINE BinaryValue::BinaryValue (StringDecoder * _dec)
    : dec (_dec), offset (0)
                                                                  {}
}
namespace sttSav
{
  LZZ_INLINE uint8_t BinaryValue::getBvType () const
                                         {
		return dec->buff[offset];
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::payloadOffset () const
                                              {
		return offset + 1;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::getJumpSize () const
                                            {
		uint32_t v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::getMemberCount () const
                                               {
		uint32_t v;
		dec->parseAt(payloadOffset() + sizeof(uint32_t), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::childOffset () const
                                            {
		return payloadOffset() + sizeof(uint32_t) * 2;
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::nextOffset () const
                                           {
		// gets the offset of the next data value after this
		switch (getBvType()) {
			case bvConstants::BV_BOOL:
			case bvConstants::BV_UINT8:
			case bvConstants::BV_INT8:
				return offset + 2;

			case bvConstants::BV_UINT16:
			case bvConstants::BV_INT16:
				return offset + 3;

			case bvConstants::BV_FLOAT:
			case bvConstants::BV_UINT32:
			case bvConstants::BV_INT32:
				return offset + 5;

			case bvConstants::BV_DOUBLE:
			case bvConstants::BV_UINT64:
			case bvConstants::BV_INT64:
				return offset + 9;

			case bvConstants::BV_STRING: {
				StringDecoder d(*dec);
				d.seek = payloadOffset();
				uint64_t sz = d.parseSize();
				return d.seek + sz;
				}

			case bvConstants::BV_ARRAY:
			case bvConstants::BV_OBJECT:
				return offset + getJumpSize();

			default:
				//STTSAV_ASSERT(false);
				return offset;
			}
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsValid () const
                                    { return dec; }
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsArray () const
                                    {
		return getBvType() == bvConstants::BV_ARRAY;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsObject () const
                                     {
		return getBvType() == bvConstants::BV_OBJECT;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsString () const
                                     {
		return getBvType() == bvConstants::BV_STRING;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsBool () const
                                   {
		return getBvType() == bvConstants::BV_BOOL;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsNumber () const
                                     {
		const uint8_t t = getBvType();
		return t >= bvConstants::BV_NUMBERS_START && t <= bvConstants::BV_NUMBERS_END;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsSignedInteger () const
                                            {
		const uint8_t t = getBvType();
		return t >= bvConstants::BV_INT8 && t <= bvConstants::BV_INT64;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsUnsignedInteger () const
                                              {
		const uint8_t t = getBvType();
		return t >= bvConstants::BV_UINT8 && t <= bvConstants::BV_UINT64;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsFloating () const
                                       {
		const uint8_t t = getBvType();
		return t >= bvConstants::BV_FLOAT && t <= bvConstants::BV_DOUBLE;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::Size () const
                                     {
		return getMemberCount();
		}
}
namespace sttSav
{
  LZZ_INLINE int8_t BinaryValue::GetInt8 () const
                                      { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE int16_t BinaryValue::GetInt16 () const
                                        { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE int32_t BinaryValue::GetInt32 () const
                                        { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE int64_t BinaryValue::GetInt64 () const
                                        { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE int32_t BinaryValue::GetInt () const
                                      { return GetInt32(); }
}
namespace sttSav
{
  LZZ_INLINE uint8_t BinaryValue::GetUint8 () const
                                        { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE uint16_t BinaryValue::GetUint16 () const
                                          { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetUint32 () const
                                          { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::GetUint64 () const
                                          {
		if (getBvType() == bvConstants::BV_UINT64) {
			uint64_t v;
			dec->parseAt(payloadOffset(), v);
			return v;
			}
		return getInteger();
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetUint () const
                                        { return GetUint32(); }
}
namespace sttSav
{
  LZZ_INLINE float BinaryValue::GetFloat () const
                                      { return getFloating(); }
}
namespace sttSav
{
  LZZ_INLINE float BinaryValue::GetDouble () const
                                       { return getFloating(); }
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::GetBool () const
                                    {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsBool());
		uint8_t v;
		dec->parseAt(payloadOffset(), v);
		return v != 0;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetStringLength () const
                                                {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsString());
		StringDecoder d(*dec);
		d.seek = payloadOffset();
		return (uint32_t)d.parseSize();
		}
}
namespace sttSav
{
  LZZ_INLINE BinaryWriter::BinaryWriter ()
    : enc (NULL)
                                          {}
}
namespace sttSav
{
  LZZ_INLINE BinaryWriter::BinaryWriter (StringEncoder * _enc)
    : enc (_enc)
                                                            {}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::onValueWritten ()
                                     {
		if (!stack.empty() && !stack.back().isObject)
			stack.back().memberCount++;
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::startContainer (uint8_t const bvType, bool const isObject)
                                                                              {
		onValueWritten();

		scope s;
		s.startOffset = enc->getSeek();
		s.memberCount = 0;
		s.isObject = isObject;
		stack.push_back(s);

		enc->parse<uint8_t>(bvType);
		enc->parse<uint32_t>(0); // Jump placeholder
		enc->parse<uint32_t>(0); // Member count placeholder
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::endContainer ()
                                   {
		STTSAV_ASSERT(!stack.empty());

		const scope s = stack.back();
		stack.pop_back();

		const uint32_t jump = uint32_t(enc->getSeek() - s.startOffset);

		enc->parseAt<uint32_t>(s.startOffset + 1, jump);
		enc->parseAt<uint32_t>(s.startOffset + 5, s.memberCount);
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void BinaryWriter::writePrimitive (uint8_t const bvType, T const value)
                                                                        {
		onValueWritten();
		enc->parse<uint8_t>(bvType);
		enc->parse<T>(value);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::StartObject ()
                                  {
		startContainer(bvConstants::BV_OBJECT, true);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::StartArray ()
                                 {
		startContainer(bvConstants::BV_ARRAY, false);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::EndObject ()
                                {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(stack.back().isObject);
		endContainer();
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::EndArray ()
                               {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(!stack.back().isObject);
		endContainer();
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Key (char const * str, uint32_t const sz)
                                                            {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(stack.back().isObject);
		stack.back().memberCount++;
		enc->parseString(str, strlen(str));
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Key (char const * str)
                                         {
		Key(str, strlen(str));
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int (int const v)
                                     { Int32(v); }
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int8 (int8_t const v)
                                         {
		writePrimitive<int8_t>(bvConstants::BV_INT8, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int16 (int16_t const v)
                                           {
		writePrimitive<int16_t>(bvConstants::BV_INT16, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int32 (int32_t const v)
                                           {
		writePrimitive<int32_t>(bvConstants::BV_INT32, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int64 (int64_t const v)
                                           {
		writePrimitive<int64_t>(bvConstants::BV_INT64, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint (unsigned int const v)
                                           { Uint32(v); }
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint8 (uint8_t const v)
                                           {
		writePrimitive<uint8_t>(bvConstants::BV_UINT8, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint16 (uint16_t const v)
                                             {
		writePrimitive<uint16_t>(bvConstants::BV_UINT16, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint32 (uint32_t const v)
                                             {
		writePrimitive<uint32_t>(bvConstants::BV_UINT32, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint64 (uint64_t const v)
                                             {
		writePrimitive<uint64_t>(bvConstants::BV_UINT64, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Float (float const v)
                                         {
		writePrimitive<float>(bvConstants::BV_FLOAT, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Double (double const v)
                                           {
		writePrimitive<double>(bvConstants::BV_DOUBLE, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Bool (bool const v)
                                       {
		writePrimitive<uint8_t>(bvConstants::BV_BOOL, v ? 1 : 0);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (char const * str, uint32_t const len)
                                                                {
		onValueWritten();
		enc->parse<uint8_t>(bvConstants::BV_STRING);
		enc->parseString(str, len);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (char const * str)
                                            {
		return String(str, strlen(str));
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (STTSAV_STRING const & str)
                                                     {
		return String(str.data(), str.size());
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#define STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#define LZZ_OVERRIDE
// binaryValueWriter.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  int64_t BinaryValue::getInteger () const
                                   {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsNumber());

		switch (getBvType()) {
			case bvConstants::BV_INT8: {
				int8_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT16: {
				int16_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT32: {
				int32_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT64: {
				int64_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT8: {
				uint8_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT16: {
				uint16_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT32: {
				uint32_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT64: {
				uint64_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_FLOAT: {
				float v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_DOUBLE: {
				double v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			default:
				STTSAV_ASSERT(false);
				return 0;
			}
		}
}
namespace sttSav
{
  double BinaryValue::getFloating () const
                                   {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsNumber());

		switch (getBvType()) {
			case bvConstants::BV_INT8: {
				int8_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT16: {
				int16_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT32: {
				int32_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT64: {
				int64_t v;
				dec->parseAt(payloadOffset(), v);
				return (double)v;
				}
			case bvConstants::BV_UINT8: {
				uint8_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT16: {
				uint16_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT32: {
				uint32_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT64: {
				uint64_t v;
				dec->parseAt(payloadOffset(), v);
				return (double)v;
				}
			case bvConstants::BV_FLOAT: {
				float v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_DOUBLE: {
				double v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			default:
				STTSAV_ASSERT(false);
				return 0.0;
			}
		}
}
namespace sttSav
{
  STTSAV_STRING BinaryValue::GetString () const
                                        {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsString());
		STTSAV_STRING out;
		GetStringRef(out);
		return out;
		}
}
namespace sttSav
{
  void BinaryValue::GetStringRef (STTSAV_STRING & out) const
                                                    {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsString());
		StringDecoder d(*dec);
		d.seek = payloadOffset();
		d.parseString(out);
		}
}
namespace sttSav
{
  BinaryValue BinaryValue::operator [] (uint32_t index) const
                                                     {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsArray());
		STTSAV_ASSERT(index < Size());

		uint64_t off = childOffset();

		for (uint32_t i = 0; i < index; ++i) {
			BinaryValue v;
			v.dec = dec;
			v.offset = off;
			off = v.nextOffset();
			}

		BinaryValue out;
		out.dec = dec;
		out.offset = off;
		return out;
		}
}
namespace sttSav
{
  void BinaryValue::findChildByKey (char const * key, uint32_t & idxOut, uint64_t & offsetOut) const
                                                                                             {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsObject());
		
		idxOut = -1;
		offsetOut = -1;
		
		uint64_t off = childOffset();
		for (uint32_t i = 0; i < Size(); ++i) {
			StringDecoder d(*dec);
			d.seek = off;
			
			STTSAV_STRING name;
			d.parseString(name);

			if (name == key) {
				idxOut = i;
				offsetOut = d.seek;
				return ;
				}
			
			BinaryValue v;
			v.dec = dec;
			v.offset = d.seek;
			off = v.nextOffset();
			}
		}
}
namespace sttSav
{
  BinaryValue BinaryValue::operator [] (char const * key) const
                                                      {
		uint32_t childIdx;
		uint64_t childOffset;
		findChildByKey(key, childIdx, childOffset);
		if (childIdx < Size()) {
			BinaryValue out;
			out.dec = dec;
			out.offset = childOffset;
			return out;
			}
		return BinaryValue();
		}
}
namespace sttSav
{
  void BinaryValue::ExtractMembers (BinaryValue * bvOut, STTSAV_STRING * keysOut) const
                                                                              {
		// Populates an array of size Size() objects
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsObject());
		
		uint64_t off = childOffset();
		for (uint32_t i = 0; i < Size(); ++i) {
			StringDecoder d(*dec);
			d.seek = off;
			
			STTSAV_STRING name;
			d.parseString(name);
			
			keysOut[i] = name;			
			BinaryValue& v = bvOut[i];
			v.dec = dec;
			v.offset = d.seek;
			off = v.nextOffset();
			}
		}
}
namespace sttSav
{
  void BinaryValue::ExtractArrayElements (BinaryValue * bvOut) const
                                                            {
		// Populates an array of values of size Size() 
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsArray());

		uint64_t off = childOffset();
		for (uint32_t i = 0; i < Size(); ++i) {
			BinaryValue& v = bvOut[i];
			v.dec = dec;
			v.offset = off;
			off = v.nextOffset();
			}
		}
}
namespace sttSav
{
  bool BinaryValue::HasMember (char const * key) const
                                              {
		if (!IsValid()) return false;
		if (!IsObject()) return false;
		uint32_t childIdx;
		uint64_t childOffset;
		findChildByKey(key, childIdx, childOffset);
		return (childIdx < Size());
		}
}
namespace sttSav
{
  STTSAV_STRING BinaryValue::toDbgString () const
                                          {
		return toDbgStringIndented(0);
		}
}
namespace sttSav
{
  STTSAV_STRING BinaryValue::toDbgPrintableString (uint32_t const indent) const
                                                                        {
		STTSAV_STRING tmp = GetString();
		if (!tmp.size())
			return tmp;
		
		bool isAsci = true;
		char* c_str = tmp.data();
		while (*c_str) {
			if (static_cast<unsigned char>(*c_str) > 127) {
				isAsci = false;
				break;
				}
			c_str++;
			}
		if (isAsci)
			return tmp;
		
		STTSAV_STRING hex;
		static const char lut[] = "0123456789abcdef";

		for (uint32_t i = 0; i < tmp.size(); ++i) {
			int i2 = i + 7;
			if ((i2 % 32) == 0) {
				hex += '\n';
				for (uint32_t id = 0; id < indent; ++id) {
					hex += "  ";
					}
				}
			else if (i) {
				hex += ' ';
				}
			unsigned char c = (unsigned char)tmp[i];
			hex += lut[c >> 4];
			hex += lut[c & 15];
			}
		return hex;
		}
}
namespace sttSav
{
  STTSAV_STRING BinaryValue::toDbgStringIndented (uint32_t indent) const
                                                                 {
		// Prints a human readable debug string
		constexpr uint32_t BUFFER_SIZE = 128;
		char buff[BUFFER_SIZE];
		STTSAV_STRING out;

		auto doIndent = [&](uint32_t n) {
			for (uint32_t i = 0; i < n; ++i)
				out += "  ";
			};

		if (!IsValid()) {
			out += "<invalid>";
			return out;
			}

		switch (getBvType()) {
			case bvConstants::BV_EMPTY:
				out += "(null)";
				break;
			case bvConstants::BV_BOOL:
				out += "(bool) ";
				out += GetBool() ? "true" : "false";
				break;
			case bvConstants::BV_INT8:
				snprintf(buff, BUFFER_SIZE, "(int8) %d", (int)GetInt8());
				out += buff;
				break;
			case bvConstants::BV_INT16:
				snprintf(buff, BUFFER_SIZE, "(int16) %d", (int)GetInt16());
				out += buff;
				break;
			case bvConstants::BV_INT32:
				snprintf(buff, BUFFER_SIZE, "(int32) %d", GetInt32());
				out += buff;
				break;
			case bvConstants::BV_INT64:
				snprintf(buff, BUFFER_SIZE, "(int64) %lld", (long long)GetInt64());
				out += buff;
				break;
			case bvConstants::BV_UINT8:
				snprintf(buff, BUFFER_SIZE, "(uint8) %u", (unsigned)GetUint8());
				out += buff;
				break;
			case bvConstants::BV_UINT16:
				snprintf(buff, BUFFER_SIZE, "(uint16) %u", (unsigned)GetUint16());
				out += buff;
				break;
			case bvConstants::BV_UINT32:
				snprintf(buff, BUFFER_SIZE, "(uint32) %u", GetUint32());
				out += buff;
				break;
			case bvConstants::BV_UINT64:
				snprintf(buff, BUFFER_SIZE, "(uint64) %llu", (unsigned long long)GetUint64());
				out += buff;
				break;
			case bvConstants::BV_FLOAT:
				snprintf(buff, BUFFER_SIZE, "(float) %g", GetFloat());
				out += buff;
				break;
			case bvConstants::BV_DOUBLE:
				snprintf(buff, BUFFER_SIZE, "(double) %g", GetDouble());
				out += buff;
				break;
			case bvConstants::BV_STRING:
				out += "(string) \"";
				out += toDbgPrintableString(indent);
				out += "\"";
				break;
			case bvConstants::BV_ARRAY:
				out += "(array)\n";
				doIndent(indent);
				out += "[\n";
				for (uint32_t i = 0; i < Size(); ++i) {
					doIndent(indent + 1);
					out += (*this)[i].toDbgStringIndented(indent + 1);
					out += "\n";
					}
				doIndent(indent);
				out += "]";
				break;
			case bvConstants::BV_OBJECT: {
				out += "(object)\n";
				doIndent(indent);
				out += "{\n";
				uint64_t off = childOffset();
				for (uint32_t i = 0; i < Size(); ++i) {
					StringDecoder d(*dec);
					d.seek = off;
					
					STTSAV_STRING key;
					d.parseString(key);

					BinaryValue child;
					child.dec = dec;
					child.offset = d.seek;

					doIndent(indent + 1);
					out += key;
					out += ": ";
					out += child.toDbgStringIndented(indent + 1);
					out += "\n";

					off = child.nextOffset();
					}

				doIndent(indent);
				out += "}";
				break;
				}
			default:
				out += "<unknown>";
				break;
			}
		return out;
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#endif //STT_SAV_IMPL_IMPL
