// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// example.hh
//

#ifndef LZZ_example_hh
#define LZZ_example_hh
// needed to build example.cpp itself
#define STT_SAV_IMPL 
#define LZZ_INLINE inline
int main (int argc, char * * argv);
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_example
#define STT_SAV_IMPL_DOUBLE_GUARD_example
#define LZZ_OVERRIDE
// example.cpp
//


// build the implementation
#define STTSAV_DBG
#define STT_SAV_IMPL
#include "stt-sav.h"
#include "binaryValueWriter.h"

// PlantartyFace archive system
#include "planetaryFaceUVArchiveDictionary.h"
#include "XYArchiveDictionary.h"

#include <map>

// Helper functions
namespace sttSav {
void testSplitting(ArchiveDictionaryI& dic, const archiveId aid, STTSAV_VECTOR<recordInfo>& records) {
	// Tests splitting a dictionary based on oversized records
	struct workItem {
		archiveId aid;
		STTSAV_VECTOR<recordInfo> records;
		};

	STTSAV_VECTOR<workItem> queue;

	workItem start;
	start.aid = aid;
	start.records = records;
	queue.push_back(start);
	
	int split = 0;

	while (!queue.empty()) {
		workItem w = std::move(queue.back());
		queue.pop_back();
		splitResult results[32];
		uint32_t numResults;

		bool ok = dic.splitArchive( w.aid, w.records, 4000, results, numResults, 32);
		
		printf("split result input %i - ok? %b\n", (int)w.aid.value, ok);
		for (uint32_t i = 0; i < numResults; ++i) 
			printf("  archive %u size %u\n", results[i].aid.value, results[i].size);
			
		if (!ok)
			continue;

		workItem next[32];
		for (uint32_t i = 0; i < numResults; ++i)
			next[i].aid = results[i].aid;

		// Redistribute records.
		for (const recordInfo& r : w.records) {
			archiveId aid = dic.getArchiveIdFromShortlist(r.key, results, numResults);

			for (uint32_t i = 0; i < numResults; ++i) {
				if (results[i].aid.value == aid.value) {
					next[i].records.push_back(r);
					break;
					}
				}
			}
		
		// Queue oversized children.
		for (uint32_t i = 0; i < numResults; ++i) {
			if (results[i].size > 4000)
				queue.push_back(std::move(next[i]));
			}
		
		// split result:
			
		// Print tree
		printf("split %i:\n", split);
		dic.dbgDump();
		split++;
		printf("\n");
		}
	}
	
void testMerging(ArchiveDictionaryI& dic, const archiveId aid, const int mergeId) {
	archiveId arBuf[32];
	uint32_t numArchives;
	
	if (dic.getMergeCandidates(aid, arBuf, numArchives, 32)) {
		bool ok = dic.mergeArchives(arBuf, numArchives);
		
		if (ok) {
			// Print tree
			printf("merge %i:\n", mergeId);
			dic.dbgDump();
			printf("\n");
			}
		else
			printf("merge %i failed\n", mergeId);
		}
	else {
		printf("merge %i failed\n", mergeId);
		}
	}
} // namespace sttSav

#define LZZ_INLINE inline
int main (int argc, char * * argv)
                                  {
	printf("Starting example...\n");
	
	// Test planetary dictionary
	using namespace sttSav;
	
	if (0) {
		// TEST - planetary down
		PlanetaryFaceUVArchiveDictionary pdic;
		ArchiveManager AM(&pdic);
		
		STTSAV_VECTOR<recordInfo> records;

		// Planet 0 (large)
		for (uint32_t i = 0; i < 50; ++i) {
			recordInfo r;
			r.key = pdic.buildKey(0, 0, 0, i % 128, i % 128);
			r.record.value = i + 1;
			r.offset = 0;
			r.length = 100;
			records.push_back(r);
			}

		// Planet 1 (medium)
		for (uint32_t i = 0; i < 30; ++i) {
			recordInfo r;
			r.key = pdic.buildKey(1, 2, 0, i % 128, i % 128);
			r.record.value = 100 + i;
			r.offset = 0;
			r.length = 100;
			records.push_back(r);
			}

		// Planet 2 (small)
		for (uint32_t i = 0; i < 10; ++i) {
			recordInfo r;
			r.key = pdic.buildKey(2, 4, 0, i % 128, i % 128);
			r.record.value = 200 + i;
			r.offset = 0;
			r.length = 100;
			records.push_back(r);
			}

		// Planet 3 (GLOBAL_FACE)
		for (uint32_t i = 0; i < 20; ++i) {
			recordInfo r;
			r.key = pdic.buildKey(3, PUVADictConstants::GLOBAL_FACE, 0, 0, 0);
			r.record.value = 300 + i;
			r.offset = 0;
			r.length = 100;
			records.push_back(r);
			}
			
		pdic.initNewDictionary();
		
		// Test splitting
		testSplitting(pdic, {pdic.root.children[0]->aid}, records);
		
		// Test merging
		testMerging(pdic, {13}, 1);
		testMerging(pdic, {2}, 2);
		testMerging(pdic, {2}, 3);
		
		// print the status of the dictionary
		//pdic.dbgDump();
		
		// Test encoding
		{
		// Encode with BinaryWriter
		STTSAV_STRING buff;
		StringEncoder enc(buff);
		BinaryWriter w(&enc);
		pdic.root.encode(w);
		
		// Debug dump the 
		StringDecoder dec(buff);
		BinaryValue v(&dec);
		printf ("pidc.root: %s\n", v.toDbgString().c_str());
		}
		}
	if (0) {
		// TEST - XY dictionary
		XYArchiveDictionary xydic;
		ArchiveManager AM(&xydic);

		STTSAV_VECTOR<recordInfo> records;

		// Large cluster (NW)
		for (uint32_t i = 0; i < 50; ++i) {
			recordInfo r;
			r.key = xydic.buildKey(-32000 + (i % 64)*8,  -32000 + (i % 64)*8);
			r.record.value = i + 1;
			r.offset = 0;
			r.length = 100;
			records.push_back(r);
			}

		// Medium cluster (SE)
		for (uint32_t i = 0; i < 30; ++i) {
			recordInfo r;
			r.key = xydic.buildKey(30000 + (i % 64)*8,  30000 + (i % 64)*8);
			r.record.value = 100 + i;
			r.offset = 0;
			r.length = 100;
			records.push_back(r);
			}

		// Small cluster (NE)
		for (uint32_t i = 0; i < 10; ++i) {
			recordInfo r;
			r.key = xydic.buildKey(30000 + (i % 64)*8, -32000 + (i % 64)*8);
			r.record.value = 200 + i;
			r.offset = 0;
			r.length = 100;
			records.push_back(r);
			}

		xydic.initNewDictionary();

		// Split repeatedly
		testSplitting(xydic, xydic.root.children[0]->aid, records);

		// Merge back together.
		testMerging(xydic, {2}, 1);
		testMerging(xydic, {2}, 2);
		testMerging(xydic, {2}, 3);
		testMerging(xydic, {2}, 4);

		// Dump final tree.
		//xydic.dbgDump();

		// Test encode/decode.
		{
			STTSAV_STRING buff;
			StringEncoder enc(buff);
			BinaryWriter w(&enc);
			xydic.root.encode(w);

			StringDecoder dec(buff);
			BinaryValue v(&dec);
			printf("xydic.root: %s\n", v.toDbgString().c_str());
		}
	}

	if (1) {
		// Test Archive Manager
		// We make a "fake" voxel game. We distribute chunks around spawn
		// of varying size. We generate random data, then save to disc
		// we then load and compare

		struct ChunkCoord {
			int32_t x;
			int32_t y;

			inline bool operator<(const ChunkCoord& o) const {
				if (x != o.x) return x < o.x;
				return y < o.y;
				}
			};

		struct ChunkData {
			recordId rid;
			STTSAV_STRING blob;
			};
		std::map<ChunkCoord, ChunkData> truth;

		srand(1);

		system("rm -rf archive-test");
		system("mkdir archive-test");

		// New save test
		{
		XYArchiveDictionary dict;
		dict.initNewDictionary();
		ArchiveManager mgr(&dict);
		mgr.mBasePath = "archive-test";
		mgr.saveDictionary();

		mgr.maxArchiveSize = 64 * 1024;
		mgr.minimumArchiveSize = 8 * 1024;
		mgr.compactionRatio = 1.5f;


		recordId nextRid = {1};

		// Generate world.
		auto makeBlob = []() {
			STTSAV_STRING s;
			uint32_t sz = 100 + rand() % 1901;
			s.resize(sz);

			for (uint32_t i = 0; i < sz; ++i)
				s[i] = rand() & 0xff;

			return s;
			};

		auto insertChunk = [&](int x, int y) {
			ChunkCoord c = {x, y};
			if (truth.count(c))
				return;

			ChunkData d;
			d.rid = nextRid;
			nextRid.value++;
			
			//if (d.rid.value == 1059) {
			//	printf("GENERATE CHUNK 1059\n");
			//	abort();
			//	}
			
			//d.blob = makeBlob();
			StringEncoder enc(d.blob);
			BinaryWriter w(&enc);
			
			w.StartObject();
				w.Key("chunkX");
				w.Int(x);
				w.Key("chunkY");
				w.Int(y);
				w.Key("blockData");
				w.String(makeBlob());
			w.EndObject();
			
			truth[c] = d;
			};

		for (int i = 0; i < 500; ++i)
			insertChunk(rand() % 64, rand() % 64);

		for (int i = 0; i < 500; ++i)
			insertChunk(rand() % 256, rand() % 256);

		// Initial save.
		for (auto& it : truth) {
			archiveKey key = dict.buildKey(it.first.x, it.first.y);
			mgr.saveRecord(key, it.second.rid, it.second.blob.data(), it.second.blob.size());
			}

		mgr.doMaintenance(false, false);

		// Verify.
		for (auto& it : truth) {
			archiveKey key = dict.buildKey(it.first.x, it.first.y);
			STTSAV_STRING blob;

			STTSAV_ASSERT(mgr.loadRecord(key,it.second.rid,blob));
			STTSAV_ASSERT(blob.size() == it.second.blob.size());
			STTSAV_ASSERT(memcmp(blob.data(),it.second.blob.data(),blob.size()) == 0);
			}

		printf( "ArchiveManager test passed 1 - splitting after generating (%zu chunks)\n", truth.size());
		
		// Mutate.
		for (int iter = 0; iter < 1000; ++iter) {
			int op = rand() % 100;

			if (truth.empty())
				op = 99;

			if (op < 60) {
				auto it = truth.begin();
				std::advance(it, rand() % truth.size());

				it->second.blob = makeBlob();

				archiveKey key = dict.buildKey(it->first.x, it->first.y);
				mgr.saveRecord( key, it->second.rid, it->second.blob.data(), it->second.blob.size());
				}
			else if (op < 80) {
				auto it = truth.begin();
				std::advance(it, rand() % truth.size());

				archiveKey key = dict.buildKey(it->first.x, it->first.y);
				mgr.deleteRecord(key, it->second.rid);

				truth.erase(it);
				}
			else {
				ChunkCoord c;

				do {
					c.x = rand() % 256;
					c.y = rand() % 256;
					}
				while (truth.count(c));

				insertChunk(c.x, c.y);
				
				auto it = truth.find(c);
				STTSAV_ASSERT(it != truth.end());
				
				archiveKey key = dict.buildKey(it->first.x, it->first.y);
				mgr.saveRecord( key, it->second.rid, it->second.blob.data(), (uint32_t)it->second.blob.size());
				}

			if ((iter % 50) == 0)
				mgr.doMaintenance(true, false);
			}

		mgr.doMaintenance(false, true);

		// Final verify.
		for (auto& it : truth) {
			archiveKey key = dict.buildKey(it.first.x, it.first.y);
			STTSAV_STRING blob;
			//printf("mgr.loadRecord: %i %i\n", key.value, it.second.rid.value );
			STTSAV_ASSERT(mgr.loadRecord( key, it.second.rid, blob));
			STTSAV_ASSERT(blob.size() == it.second.blob.size());
			STTSAV_ASSERT(memcmp( blob.data(), it.second.blob.data(), blob.size()) == 0);
			}

		printf( "ArchiveManager test passed 2 - after mutating (%zu chunks)\n", truth.size());
		}
		
		// Load archive test
		{
		XYArchiveDictionary dict;
		ArchiveManager mgr(&dict);
		mgr.mBasePath = "archive-test";
		mgr.loadDictionary();
		
		//dict.dbgDump();

		//verify.
		for (auto& it : truth) {
			archiveKey key = dict.buildKey(it.first.x, it.first.y);
			STTSAV_STRING blob;
			//printf("mgr.loadRecord: %i %i\n", key.value, it.second.rid.value );
			STTSAV_ASSERT(mgr.loadRecord( key, it.second.rid, blob));
			STTSAV_ASSERT(blob.size() == it.second.blob.size());
			STTSAV_ASSERT(memcmp( blob.data(), it.second.blob.data(), blob.size()) == 0);
			}

		printf( "ArchiveManager test passed 3 - loading fresh (%zu chunks)\n", truth.size());
		}
		
		}
		
	

	printf("Exiting example...\n");
	return 0;
	}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_example
#endif //STT_SAV_IMPL_IMPL
