// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// inspect.hh
//

#ifndef LZZ_inspect_hh
#define LZZ_inspect_hh
// needed to build inspect.cpp itself
#define STT_SAV_IMPL 
#define LZZ_INLINE inline
int main (int argc, char * * argv);
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_inspect
#define STT_SAV_IMPL_DOUBLE_GUARD_inspect
#define LZZ_OVERRIDE
// inspect.cpp
//

#include "3rdParty/ftxui.hpp"
//#include "3rdParty/ftxui.cpp"

// build the implementation
#define STTSAV_DBG
#define STT_SAV_IMPL
#include "stt-sav.h"
#include "binaryValueWriter.h"

// PlantartyFace archive system
#include "planetaryFaceUVArchiveDictionary.h"
#include "XYArchiveDictionary.h"

#include <thread>
#include <mutex>
#include <condition_variable>
#include <deque>

enum PreviewType {
	PREVIEW_BLOB,
	PREVIEW_BINARY_VALUE,
	PREVIEW_ASCII,
	PREVIEW_UTF8
	};
	
struct RecordPreview {
	PreviewType type;
	STTSAV_STRING blob;
	sttSav::BinaryValue binaryValue;
	STTSAV_STRING ascii;
	STTSAV_STRING utf8;
	
	RecordPreview() : type(PREVIEW_BLOB) {}
	};

struct ArchiveEntry {
    sttSav::archiveId aid;
    STTSAV_STRING filename;
	};

struct ArchivePreview {
	STTSAV_VECTOR<sttSav::recordInfo> records;
	STTSAV_VECTOR<RecordPreview*> recordPreviews;
	uint64_t totalBytes;
	uint64_t wastedBytes;
	uint64_t fileLength;
	RecordPreview preview;
	bool isArchive;
	
	inline ArchivePreview() : totalBytes(0), wastedBytes(0), fileLength(0), isArchive(false) {}
	
	void destroyRecords() {
		for (RecordPreview* P : recordPreviews)
			delete P;
		records.clear();
		recordPreviews.clear();
		}
	
	~ArchivePreview() {
		destroyRecords();
		}
	};

enum UiMode {
	UI_ARCHIVES,
	UI_RECORDS
	};
	
void processPreview(RecordPreview& preview) {
	preview.type = PREVIEW_BLOB;

	const STTSAV_STRING& blob = preview.blob;

	if (blob.empty())
		return;

	using namespace sttSav;
	StringDecoder d(blob);
	BinaryValue bv(&d);
	
	// test array or object
	if (blob.size() >= 5) {
		if (bv.nextOffset() == blob.size()) {
			if (bv.IsArray()) {
				// test if (bv.next is end of stream)
				preview.type = PREVIEW_BINARY_VALUE;
				preview.binaryValue = bv;
				preview.binaryValue.dec = NULL;
				return;
				}
			else if (bv.IsObject()) {
				preview.type = PREVIEW_BINARY_VALUE;
				preview.binaryValue = bv;
				preview.binaryValue.dec = NULL;
				return;
				}
			}
		}

	// ASCII?
	bool ascii = true;
	for (unsigned char c : blob) {
		// Printable ASCII plus common whitespace.
		if (c == '\n' ||
			c == '\r' ||
			c == '\t')
			continue;
		if (c < 32 || c > 126) {
			ascii = false;
			break;
			}
		}
	if (ascii) {
		preview.type = PREVIEW_ASCII;
		preview.ascii = blob;
		return;
		}

	// Fallback
	preview.type = PREVIEW_BLOB;
	}
	
bool loadPreview(sttSav::ArchiveManager* AM, const STTSAV_STRING& manualFilename, const sttSav::archiveId aid, ArchivePreview& preview) {
	// Loads a preview
	preview.destroyRecords();
	preview.totalBytes = 0;
	preview.wastedBytes = 0;
	preview.fileLength = 0;
	
	if (AM) {
		sttSav::ArchiveFile* archive = AM->getLazy(aid);
		if (!archive)
			return false;

		if (!archive->hasLoadedRecords) {
			if (!archive->loadRecords())
				return false;
			}

		preview.records = archive->records;
		preview.recordPreviews.resize(preview.records.size(), NULL);

		for (const sttSav::recordInfo& r : preview.records)
			preview.totalBytes += r.length;

		preview.wastedBytes = archive->wastedBytes;
		preview.fileLength = archive->fileLength;
		preview.isArchive = true;
		}
	else {
		sttSav::FileHandle f;
		if (!f.openRead(manualFilename.c_str()))
			return false;

		preview.fileLength = f.length();
		preview.preview.blob.resize(preview.fileLength);
		if (preview.fileLength) {
			if (!f.read(preview.preview.blob.data(), preview.fileLength)) {
				f.close();
				return false;
				}
			}

		f.close();
		preview.isArchive = false;
		processPreview(preview.preview);
		}
	return true;
	}
	
bool loadRecord(sttSav::ArchiveManager& AM, const sttSav::archiveKey key,  const sttSav::recordId record, RecordPreview& preview) {
	preview = RecordPreview();
	if (!AM.loadRecord(key, record, preview.blob))
		return false;

	processPreview(preview);
	return true;
	}

enum FocusPane {
    FOCUS_LEFT,
    FOCUS_RIGHT
};

#define LZZ_INLINE inline
int main (int argc, char * * argv)
                                {
	using namespace sttSav;

	printf("sttSav Inspector\n");

	// Parse arguments.
	if (argc != 2 || !strcmp(argv[1], "-h") || !strcmp(argv[1], "--help")) {
		printf("Usage:\n"
			"    inspect <save-directory>\n\n"
			"Example:\n"
			"    inspect game0.d\n");
		return 0;
		}

	const STTSAV_STRING saveDir = FileOps::stripTrailingSlashes(argv[1]);

	if (!FileOps::isDirectory(saveDir.c_str())) {
		printf("Error: '%s' is not a directory.\n", saveDir.c_str());
		return 1;
		}

	// Read dictionary.sav.
	const STTSAV_STRING dictionaryFilename = FileOps::joinPath(saveDir, "dictionary.sav");

	if (!FileOps::exists(dictionaryFilename.c_str())) {
		printf("Error: dictionary.sav not found.\n");
		return 1;
		}

	FileHandle f;
	if (!f.openRead(dictionaryFilename.c_str())) {
		printf("Error: Unable to open dictionary.sav\n");
		return 1;
		}

	STTSAV_STRING dictionaryBlob;
	dictionaryBlob.resize(f.length());
	if (!f.read(dictionaryBlob.data(), dictionaryBlob.size())) {
		printf("Error: Unable to read dictionary.sav\n");
		return 1;
		}
	f.close();

	// Peek dictionary type.
	StringDecoder dec(dictionaryBlob);
	BinaryValue root(&dec);

	STTSAV_STRING dictionaryType;
	if (root.HasMember("dictionaryType"))
		dictionaryType = root["dictionaryType"].GetString();
	printf("Dictionary: %s\n", dictionaryType.c_str());

	// Create dictionary.
	ArchiveDictionaryI* dictionary = NULL;

	if (dictionaryType == "XYArchiveDictionary")
		dictionary = STTSAV_NEW(XYArchiveDictionary);
	else if (dictionaryType == "PlanetaryFaceUVArchiveDictionary")
		dictionary = STTSAV_NEW(PlanetaryFaceUVArchiveDictionary);
	else if (dictionaryType == "T2PlanetaryFaceUVArchiveDictionary")
		dictionary = STTSAV_NEW(T2PlanetaryFaceUVArchiveDictionary);

	if (!dictionary) {
		printf("Error: Unknown dictionary type '%s'\n", dictionaryType.c_str());
		return 1;
		}

	dictionary->decodeDictionary(dictionaryBlob); //decodeDictionary returns number of records
	//if (!dictionary->decodeDictionary(dictionaryBlob)) {
	//	printf("Error: Failed to decode dictionary.\n");
	//	STTSAV_DEL(dictionary, sizeof(*dictionary));
	//	return 1;
	//	}

	// Initialise ArchiveManager.
	ArchiveManager archiveManager(dictionary);
	archiveManager.mBasePath = saveDir;
	archiveManager.initArchiveFilesFromDictionary();

	// Build archive list.
	STTSAV_VECTOR<ArchiveEntry> archives;
	
	ArchiveEntry e;
	e.aid = {0};
	e.filename = FileOps::joinPath(saveDir, "dictionary.sav");
	archives.push_back(e);
	
	for (ArchiveFile* af : archiveManager.mArchives) {
		if (!af)
			continue;
		if (!af->fileExists)
			continue;
		ArchiveEntry e;
		e.aid = af->aid;
		e.filename = af->filename;
		//printf("\tArchive %s.\n", e.filename.c_str());
		archives.push_back(e);
		}

	printf("Loaded %zu archives.\n", archives.size());

	// Init worker thread	

	UiMode mode = UI_ARCHIVES;
	int selectedArchive = 0;
	int selectedRecord = 0;

	ArchivePreview currentPreview;
	
	if (selectedArchive >= 0 && selectedArchive < (int)archives.size()) {
		if (archives[selectedArchive].aid.value)
			loadPreview(&archiveManager, archives[selectedArchive].filename, archives[selectedArchive].aid, currentPreview);
		else
			loadPreview(NULL, archives[selectedArchive].filename, archives[selectedArchive].aid, currentPreview);
		}
	
	// Used to truncate "archive-test/" from every directory
	const uint32_t directoryLen = saveDir.length() + 1;

	// Launch the FTXUI interface.
	{ // FTXUI Loop Begin
	using namespace ftxui;

	FocusPane focus = FOCUS_LEFT;
	float previewScroll = 0.f;

	std::vector<std::string> archiveNames;
	for (const ArchiveEntry& a : archives) {
		char buff[512];
		snprintf(buff, sizeof(buff), "%4u %s ", (unsigned)a.aid.value, a.filename.c_str() + directoryLen);
		archiveNames.push_back(buff);
		}

	std::string previewText = 
		"Select an archive.\n\n"
		"Press Enter to inspect it.\n"
		"Esc exits.";

	std::vector<std::string> leftItems;

	// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Build left column
	auto rebuildLeftItems = [&]() {
		leftItems.clear();

		for (const sttSav::recordInfo& r : currentPreview.records) {
			char buff[128];
			snprintf(buff, sizeof(buff), "%08X %08X ", (unsigned)r.key.value, (unsigned)r.record.value);
			leftItems.push_back(buff);
			}
		};

	rebuildLeftItems();
	
	auto archiveMenu = Menu(&archiveNames, &selectedArchive);
	auto recordMenu  = Menu(&leftItems,    &selectedRecord);

	// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Render
	auto previewRenderer = Renderer([&] {
		if (mode == UI_ARCHIVES) {
			if (archives.empty())
				return text("No archives.");
			const ArchiveEntry& a = archives[selectedArchive];
			Elements elems;
			elems.push_back(text("Archive Preview") | bold);
			elems.push_back(separator());
			elems.push_back(text("Archive Id : " + std::to_string(a.aid.value)));
			elems.push_back(text("Filename   : " + a.filename));
			elems.push_back(separator());

			{
				char buff[256];
				snprintf(buff,sizeof(buff),"Records     : %u", (unsigned)currentPreview.records.size());
				elems.push_back(text(buff));
				snprintf(buff,sizeof(buff),"Live Bytes  : %llu", (unsigned long long)currentPreview.totalBytes);
				elems.push_back(text(buff));
				snprintf(buff,sizeof(buff),"Wasted      : %llu", (unsigned long long)currentPreview.wastedBytes);
				elems.push_back(text(buff));
				snprintf(buff,sizeof(buff),"File Size   : %llu", (unsigned long long)currentPreview.fileLength);
				elems.push_back(text(buff));
			}

			return vbox(std::move(elems));
			}

		// Record view.
		const RecordPreview* rp = NULL;
		Elements elems;

		if (currentPreview.isArchive) {
			if (currentPreview.records.empty())
				return text("Archive contains no records.");

			if (selectedRecord >= 0 || selectedRecord < (int)currentPreview.records.size()) {
				const sttSav::recordInfo& r = currentPreview.records[selectedRecord];

				char buff[256];
				elems.push_back(text("Record Preview") | bold);
				elems.push_back(separator());
				snprintf(buff,sizeof(buff),"Key    : 0x%08X", (unsigned)r.key.value);
				elems.push_back(text(buff));
				snprintf(buff,sizeof(buff),"RecordId : 0x%08X", (unsigned)r.record.value);
				elems.push_back(text(buff));
				snprintf(buff,sizeof(buff),"Offset : %u", (unsigned)r.offset);
				elems.push_back(text(buff));
				snprintf(buff,sizeof(buff),"Length : %u", (unsigned)r.length);
				elems.push_back(text(buff));
				elems.push_back(separator());
				rp = currentPreview.recordPreviews[selectedRecord]; // populated by previewRecord()
				}
			}
		else {
			char buff[256];
			elems.push_back(text("File Preview") | bold);
			elems.push_back(separator());
			snprintf(buff,sizeof(buff),"Length : %u", (unsigned)currentPreview.preview.blob.size());
			elems.push_back(text(buff));
			elems.push_back(separator());
			rp = &currentPreview.preview;
			}
		
		if (rp) {
			switch (rp->type) {
				case PREVIEW_BINARY_VALUE:
					{
					elems.push_back(text("<sttSav::BinaryValue>"));
					
					StringDecoder d(rp->blob);
					BinaryValue bv = rp->binaryValue;
					bv.dec = &d;
					
					STTSAV_STRING str = bv.toDbgString();
					
					elems.push_back(text(str.c_str()));
					}
					break;

				case PREVIEW_ASCII:
					elems.push_back(text("<ascii>"));
					elems.push_back(separator());
					elems.push_back(paragraph(rp->ascii));
					break;
				case PREVIEW_UTF8:
					elems.push_back(text("<utf8>"));
					elems.push_back(separator());
					elems.push_back(paragraph(rp->utf8));
					break;
				case PREVIEW_BLOB:
				default: {
					elems.push_back(text("<blob>"));
					elems.push_back(separator());
					std::string hex;
					static const char lut[] = "0123456789abcdef";

					const STTSAV_STRING& blob = rp->blob;
					
					for (size_t i = 0; i < blob.size(); ++i) {
						if (i && (i % 32) == 0)
							hex += '\n';
						else if (i && (i % 32) != 0)
							hex += ' ';
						unsigned char c = (unsigned char)blob[i];
						hex += lut[c >> 4];
						hex += lut[c & 15];
						}
					
					elems.push_back(paragraph(hex));
					break;
					}
				}
			}
		return vbox(std::move(elems));
		});

	auto statusBar = Renderer([&] {
		char left[256];
		char right[128];
		left[0] = 0;
		right[0] = 0;
		
		if (mode == UI_ARCHIVES) {
			snprintf(left, sizeof(left), "Archive %u/%u", selectedArchive + 1, (unsigned)archives.size());
			snprintf(right, sizeof(right), "Enter Open   q Quit");
			}
		else {
			if (selectedRecord < (int)currentPreview.records.size() && selectedRecord >= 0) {
				const auto& r = currentPreview.records[selectedRecord];
				snprintf(left, sizeof(left), "Key=%u (0x%08X)  Record=%u (0x%08X)", r.key.value, r.key.value, r.record.value, r.record.value);
				snprintf(right, sizeof(right), "%u/%u   <- Back   q Quit", selectedRecord + 1, (unsigned)currentPreview.records.size());
				}
			}

		return hbox({ text(left), filler(), text(right), });// | border;
	});

	auto leftContainer = Container::Tab({
		archiveMenu,
		recordMenu,
	}, reinterpret_cast<int*>(&mode));
	

	const float previewScrollIncr = 0.05f;
	
	previewRenderer |= CatchEvent([&](Event event) {
		if (event == Event::ArrowUp) {
			previewScroll -= previewScrollIncr;
			if (previewScroll < 0.0f)
				previewScroll = 0.0f;
			return true;
			}

		if (event == Event::ArrowDown) {
			previewScroll += previewScrollIncr;
			if (previewScroll > 1.0f)
				previewScroll = 1.0f;
			return true;
			}

		if (event == Event::PageUp) {
			previewScroll -= previewScrollIncr*16;
			if (previewScroll < 0.0f)
				previewScroll = 0.0f;
			return true;
			}

		if (event == Event::PageDown) {
			previewScroll += previewScrollIncr*16;
			if (previewScroll > 1.0f)
				previewScroll = 1.0f;
			return true;
			}

		if (event == Event::Home) {
			previewScroll = 0.0f;
			return true;
			}

		if (event == Event::End) {
			previewScroll = 1.0f;
			return true;
			}
				
		if (event.is_mouse()) {
			const auto& mouse = event.mouse();

			if (mouse.button == Mouse::WheelUp) {
				previewScroll -= previewScrollIncr;
				if (previewScroll < 0.0f)
					previewScroll = 0.0f;
				return true;
				}

			if (mouse.button == Mouse::WheelDown) {
				previewScroll += previewScrollIncr;
				if (previewScroll > 1.0f)
					previewScroll = 1.0f;
				return true;
				}
			}
		return false;
		});
		
	auto container = Container::Horizontal({
		leftContainer,
		previewRenderer,
	});
	
	auto topBar = Renderer([&] {
		STTSAV_STRING title;

		if (mode == UI_ARCHIVES)
			title = saveDir;
		else
			title = archives[selectedArchive].filename;

		return text(title) ;//| border;
	});
		
	auto root = Renderer(container, [&] {
		Element leftPane;

		if (focus == FOCUS_LEFT) {
			leftPane = window(
					text(mode == UI_ARCHIVES ? " Archives " : " Records "),
					leftContainer->Render() | vscroll_indicator | frame
				);
			}
		
		Element rightPane = window( text(" Preview "),
			previewRenderer->Render() | focusPositionRelative(0.f, previewScroll) | vscroll_indicator  | frame 
			);
				
		if (focus == FOCUS_LEFT) {
			return vbox({
				topBar->Render(),
				hbox({ std::move(leftPane), std::move(rightPane) | flex, }) | flex,
				statusBar->Render(),
			});
			}
		else {
			return vbox({
				topBar->Render(),
				hbox({	std::move(rightPane) | flex, }) | flex ,
				statusBar->Render(),
			});
			}
	});

	auto screen = ScreenInteractive::Fullscreen();

	// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Event handling	
	root |= CatchEvent([&](Event event) {

		if (event == Event::Escape || event == Event::Character('q')) {
			screen.Exit();
			return true;
			}

		const int oldArchive = selectedArchive;
		const int oldRecord = selectedRecord;
		
		bool handled = container->OnEvent(event);

		if (mode == UI_ARCHIVES && selectedArchive != oldArchive) {
			if (selectedArchive >= 0 && selectedArchive < (int)archives.size()) {
				if (archives[selectedArchive].aid.value)
					loadPreview(&archiveManager, archives[selectedArchive].filename, archives[selectedArchive].aid, currentPreview);
				else
					loadPreview(NULL, archives[selectedArchive].filename, archives[selectedArchive].aid, currentPreview);
				}
			}

		if (selectedRecord < 0) selectedRecord = 0;
		if (mode == UI_RECORDS && selectedRecord != oldRecord) {
			if (selectedRecord >= 0 && selectedRecord < (int)currentPreview.records.size()) {
				const sttSav::recordInfo& r = currentPreview.records[selectedRecord];
				if (!currentPreview.recordPreviews[selectedRecord])
					currentPreview.recordPreviews[selectedRecord] = STTSAV_NEW(RecordPreview);
				loadRecord(archiveManager, r.key, r.record, *currentPreview.recordPreviews[selectedRecord]);
				}
			}

		// Enter archive.
		if ((event == Event::Return || event == Event::ArrowRight) && mode == UI_ARCHIVES) {
			mode = UI_RECORDS;
			selectedRecord = 0;
			rebuildLeftItems();
			
			if (selectedRecord >= 0 && selectedRecord < (int)currentPreview.records.size()) {
				const sttSav::recordInfo& r = currentPreview.records[selectedRecord];
				if (!currentPreview.recordPreviews[selectedRecord])
					currentPreview.recordPreviews[selectedRecord] = STTSAV_NEW(RecordPreview);
				loadRecord(archiveManager, r.key, r.record, *currentPreview.recordPreviews[selectedRecord]);
				}
			return true;
			}
		if ((event == Event::Return || event == Event::ArrowRight) && mode == UI_RECORDS) {
			focus = FOCUS_RIGHT;
			previewRenderer->TakeFocus();
			return true;
			}

		// Leave archive.
		if ((event == Event::ArrowLeft || event == Event::Backspace) && mode == UI_RECORDS) {
			if (focus == FOCUS_RIGHT)
				focus = FOCUS_LEFT;
			else
				mode = UI_ARCHIVES;
			leftContainer->TakeFocus();
			rebuildLeftItems();
			return true;
			}

		return handled;
		});

	screen.Loop(root);
	} // FTXUI Loop End
	
	STTSAV_DEL(dictionary, sizeof(*dictionary));

	return 0;
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_inspect
#endif //STT_SAV_IMPL_IMPL
