// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// planetaryFaceUVArchiveDictionary.hh
//

#ifndef LZZ_planetaryFaceUVArchiveDictionary_hh
#define LZZ_planetaryFaceUVArchiveDictionary_hh
namespace sttSav {
	
struct PUVADictConstants {
	constexpr static uint32_t PLANET_BITS =  13;
	constexpr static uint32_t FACE_BITS   =  3;
	constexpr static uint32_t FLAGS_BITS  =  2;
	constexpr static uint32_t LOCAL_U_BITS = 7;
	constexpr static uint32_t LOCAL_V_BITS = 7;

	constexpr static uint32_t PLANET_SHIFT = 0;
	constexpr static uint32_t FACE_SHIFT  = PLANET_SHIFT + PLANET_BITS;
	constexpr static uint32_t FLAGS_SHIFT = FACE_SHIFT + FACE_BITS;
	constexpr static uint32_t LOCAL_U_SHIFT = FLAGS_SHIFT + FLAGS_BITS;
	constexpr static uint32_t LOCAL_V_SHIFT = LOCAL_U_SHIFT + LOCAL_U_BITS;

	constexpr static uint32_t PLANET_MASK = (1u << PLANET_BITS) - 1;
	constexpr static uint32_t FACE_MASK =   (1u << FACE_BITS) - 1;
	constexpr static uint32_t FLAGS_MASK =  (1u << FLAGS_BITS) - 1;
	constexpr static uint32_t LOCAL_U_MASK = (1u << LOCAL_U_BITS) - 1;
	constexpr static uint32_t LOCAL_V_MASK = (1u << LOCAL_V_BITS) - 1;

	constexpr static uint32_t NUM_FACES = 8;
	constexpr static uint32_t ROOT_UV_SIZE = 128;
	
	constexpr static uint32_t GLOBAL_FACE = 6; // not attached to cube, instead attached freely to planet
	
	constexpr static uint8_t NODE_TYPE_UNKNOWN = 0;
	constexpr static uint8_t NODE_TYPE_ROOT = 1;
	constexpr static uint8_t NODE_TYPE_PLANET = 2;
	constexpr static uint8_t NODE_TYPE_FACE = 3;
	constexpr static uint8_t NODE_TYPE_LEAF = 4;
	//constexpr static uint8_t NODE_TYPE_ROOT_ALL // not applicable
	constexpr static uint8_t NODE_TYPE_REMAINDER_FLAG = 1 << 7;
	constexpr static uint8_t NODE_TYPE_PLANET_REMAINDER = NODE_TYPE_PLANET | NODE_TYPE_REMAINDER_FLAG;
	constexpr static uint8_t NODE_TYPE_FACE_REMAINDER = NODE_TYPE_FACE | NODE_TYPE_REMAINDER_FLAG;
	constexpr static uint8_t NODE_TYPE_LEAF_REMAINDER = NODE_TYPE_LEAF | NODE_TYPE_REMAINDER_FLAG;
	
	static const char* nodeTypeToString(const uint8_t nt) {
		switch (nt) {
			case NODE_TYPE_ROOT: return "ROOT";
			case NODE_TYPE_PLANET: return "PLANET";
			case NODE_TYPE_FACE: return "FACE";
			case NODE_TYPE_LEAF: return "LEAF";
			case NODE_TYPE_PLANET_REMAINDER: return "PLANET-R";
			case NODE_TYPE_FACE_REMAINDER: return "FACE-R";
			case NODE_TYPE_LEAF_REMAINDER: return "LEAF-R";
			default: return "(unknown)";
			}
		}
	};
	
} // namespace sttSav

#ifndef STTSAV_VECTOR_PLANETNODE
	#define STTSAV_VECTOR_PLANETNODE STTSAV_VECTOR
#endif
#define LZZ_INLINE inline
namespace sttSav
{
  class PlanetaryFaceUVArchiveDictionary : public ArchiveDictionaryI
  {
  public:
    struct unpackedKey
    {
      uint16_t planet;
      uint8_t face;
      uint8_t flags;
      uint8_t localU;
      uint8_t localV;
      unpackedKey ();
      unpackedKey (uint16_t const _planet, uint8_t const _face, uint8_t const _flags, uint8_t const _localU, uint8_t const _localV);
      unpackedKey (archiveKey const key);
      archiveKey buildKey () const;
    };
    struct node
    {
      archiveId aid;
      uint16_t planet;
      uint8_t type;
      uint8_t face;
      uint8_t flags;
      uint8_t u;
      uint8_t v;
      uint8_t uvSize;
      node * parent;
      STTSAV_VECTOR_PLANETNODE <node*> children;
      node ();
      ~ node ();
      bool canSplit () const;
      bool containsExact (unpackedKey const & k) const;
      bool isRemainder () const;
      void dumpNode (int const depth) const;
    };
    struct nodeLookup
    {
      archiveId aid;
      node * ptr;
    };
    STTSAV_VECTOR <nodeLookup> mLookup;
    node root;
    PlanetaryFaceUVArchiveDictionary ();
    ~ PlanetaryFaceUVArchiveDictionary ();
    void initNewDictionary ();
    archiveKey buildKey (uint16_t const planet, uint8_t const face, uint8_t const flags, uint8_t const localU, uint8_t const localV) const;
    void reserveIds (uint32_t const numIds);
    archiveId getNextId ();
    archiveId getArchiveId (archiveKey const key) const;
    node * getNodeByArchiveId (archiveId const aid) const;
    void insertLookup (node * n);
    void clearLookup (archiveId const aid);
    static node * lookup (node * start, unpackedKey const & key);
    void getArchiveFilename (archiveId const id, char * nameOut, uint32_t & lenOut, uint32_t const maxLen) const;
    bool splitArchive (archiveId const id, STTSAV_VECTOR <recordInfo> const & records, uint32_t const maxArchiveSize, splitResult * resultsOut, uint32_t & numResultsOut, uint32_t const maxResultsOut);
    bool getMergeCandidates (archiveId const id, archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut) const;
    bool mergeArchives (archiveId const * archives, uint32_t const numArchives);
  };
}
namespace sttSav
{
  LZZ_INLINE PlanetaryFaceUVArchiveDictionary::unpackedKey::unpackedKey ()
    : planet (0), face (0), flags (0), localU (0), localV (0)
                                                                                          {}
}
namespace sttSav
{
  LZZ_INLINE PlanetaryFaceUVArchiveDictionary::unpackedKey::unpackedKey (uint16_t const _planet, uint8_t const _face, uint8_t const _flags, uint8_t const _localU, uint8_t const _localV)
    : planet (_planet), face (_face), flags (_flags), localU (_localU), localV (_localV)
                                                                                                      {}
}
namespace sttSav
{
  LZZ_INLINE PlanetaryFaceUVArchiveDictionary::unpackedKey::unpackedKey (archiveKey const key)
                                                         {
			planet = (key.value >> PUVADictConstants::PLANET_SHIFT) & PUVADictConstants::PLANET_MASK;
			face =  (key.value >> PUVADictConstants::FACE_SHIFT) & PUVADictConstants::FACE_MASK;
			flags = (key.value >> PUVADictConstants::FLAGS_SHIFT) & PUVADictConstants::FLAGS_MASK;
			localU = (key.value >> PUVADictConstants::LOCAL_U_SHIFT) & PUVADictConstants::LOCAL_U_MASK;
			localV = (key.value >> PUVADictConstants::LOCAL_V_SHIFT) & PUVADictConstants::LOCAL_V_MASK;
			}
}
namespace sttSav
{
  LZZ_INLINE archiveKey PlanetaryFaceUVArchiveDictionary::unpackedKey::buildKey () const
                                                   {
			archiveKey ret;
			ret.value = ((uint32_t(planet) & PUVADictConstants::PLANET_MASK) << PUVADictConstants::PLANET_SHIFT)
					  | ((uint32_t(face) & PUVADictConstants::FACE_MASK) << PUVADictConstants::FACE_SHIFT)
					  | ((uint32_t(flags) & PUVADictConstants::FLAGS_MASK) << PUVADictConstants::FLAGS_SHIFT)
					  | ((uint32_t(localU) & PUVADictConstants::LOCAL_U_MASK) << PUVADictConstants::LOCAL_U_SHIFT)
					  | ((uint32_t(localV) & PUVADictConstants::LOCAL_V_MASK) << PUVADictConstants::LOCAL_V_SHIFT);
			return ret;
			}
}
namespace sttSav
{
  LZZ_INLINE bool PlanetaryFaceUVArchiveDictionary::node::isRemainder () const
                                                { return type & PUVADictConstants::NODE_TYPE_REMAINDER_FLAG; }
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_planetaryFaceUVArchiveDictionary
#define STT_SAV_IMPL_DOUBLE_GUARD_planetaryFaceUVArchiveDictionary
#define LZZ_OVERRIDE
// planetaryFaceUVArchiveDictionary.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  PlanetaryFaceUVArchiveDictionary::node::node ()
                        {
			aid.value = 0;
			planet = 0;
			type = PUVADictConstants::NODE_TYPE_UNKNOWN;
			face = 0; flags = 0; u = 0; v = 0; uvSize = 0;
			parent = NULL;
			}
}
namespace sttSav
{
  PlanetaryFaceUVArchiveDictionary::node::~ node ()
                         {
			for (node* n : children)
				STTSAV_DEL(n, sizeof(node));
			}
}
namespace sttSav
{
  bool PlanetaryFaceUVArchiveDictionary::node::canSplit () const
                                      {
			// is this permitted to split under any circumstances?
			if (type == PUVADictConstants::NODE_TYPE_FACE && face == PUVADictConstants::GLOBAL_FACE)
				return false;
			return true;
			}
}
namespace sttSav
{
  bool PlanetaryFaceUVArchiveDictionary::node::containsExact (unpackedKey const & k) const
                                                               {
			// Returns true if this node contains this key exactly
			if (isRemainder())
				return false;
			
			switch (type) {
				case PUVADictConstants::NODE_TYPE_ROOT:
					return true;
				case PUVADictConstants::NODE_TYPE_PLANET:
					if (planet != k.planet)
						return false;
					return flags == k.flags;
				case PUVADictConstants::NODE_TYPE_FACE:
					if (planet != k.planet || face != k.face)
						return false;
					return flags == k.flags;
				case PUVADictConstants::NODE_TYPE_LEAF:
					if (planet != k.planet || face != k.face || flags != k.flags)
						return false;
					return k.localU >= u && k.localU < u + uvSize &&
						   k.localV >= v && k.localV < v + uvSize;
				default:
					STTSAV_ASSERT(false);
					return false;
				}
			}
}
namespace sttSav
{
  void PlanetaryFaceUVArchiveDictionary::node::dumpNode (int const depth) const
                                                     {
			#ifdef STTSAV_DBG
			for (int i = 0; i < depth; ++i)
				printf(" ");
			if ((type & PUVADictConstants::NODE_TYPE_LEAF) == PUVADictConstants::NODE_TYPE_LEAF)
				printf("type %s, id %i, p %i, f %i, u %i, v %i, uvSz %i", PUVADictConstants::nodeTypeToString(type), (int)aid.value, (int) planet, (int)face, (int)u, (int)v, (int)uvSize);
			else
				printf("type %s, id %i, p %i, f %i", PUVADictConstants::nodeTypeToString(type), (int)aid.value, (int) planet, (int)face);
			if (parent)
				printf(" [parent: %s %i]", PUVADictConstants::nodeTypeToString(parent->type), (int) parent->aid.value);
			printf("\n");
			for (const node* const n : children)
				n->dumpNode(depth + 1);
			#endif
			}
}
namespace sttSav
{
  PlanetaryFaceUVArchiveDictionary::PlanetaryFaceUVArchiveDictionary ()
                                           {
		root.type = PUVADictConstants::NODE_TYPE_ROOT;
		}
}
namespace sttSav
{
  PlanetaryFaceUVArchiveDictionary::~ PlanetaryFaceUVArchiveDictionary ()
                                            {}
}
namespace sttSav
{
  void PlanetaryFaceUVArchiveDictionary::initNewDictionary ()
                                 {
		// creates an initial node for a new dictionary
		node* n = STTSAV_NEW(node);
		n->aid = getNextId();
		n->type = PUVADictConstants::NODE_TYPE_PLANET_REMAINDER;
		n->parent = &root;
		root.children.push_back(n);
		insertLookup(n);
		}
}
namespace sttSav
{
  archiveKey PlanetaryFaceUVArchiveDictionary::buildKey (uint16_t const planet, uint8_t const face, uint8_t const flags, uint8_t const localU, uint8_t const localV) const
                                                                                                                                              {
		return unpackedKey(planet, face, flags, localU, localV).buildKey();
		}
}
namespace sttSav
{
  void PlanetaryFaceUVArchiveDictionary::reserveIds (uint32_t const numIds)
                                               {
		if (numIds <= mLookup.size()) return;
		uint32_t start = mLookup.size();
		mLookup.resize(numIds);
		for (uint32_t i = start; i < numIds; ++i) {
			mLookup[i].aid.value = i + 1;
			mLookup[i].ptr = NULL;
			}
		}
}
namespace sttSav
{
  archiveId PlanetaryFaceUVArchiveDictionary::getNextId ()
                              {
		for (uint32_t i = 0; i < mLookup.size(); ++i) {
			if (mLookup[i].ptr == NULL)
				return mLookup[i].aid;
			}
		// all slots are full
		nodeLookup l;
		l.aid.value = mLookup.size()+1;
		l.ptr = NULL;
		mLookup.push_back(l);
		return l.aid;
		}
}
namespace sttSav
{
  archiveId PlanetaryFaceUVArchiveDictionary::getArchiveId (archiveKey const key) const
                                                           {
		// Searches the entire tree for an archive for a specified key
		node* n = lookup(const_cast<node*>(&root), key);
		if (n)
			return n->aid;
		return {0};
		}
}
namespace sttSav
{
  PlanetaryFaceUVArchiveDictionary::node * PlanetaryFaceUVArchiveDictionary::getNodeByArchiveId (archiveId const aid) const
                                                             {
		if (aid.value && aid.value-1 < mLookup.size())
			return mLookup[aid.value-1].ptr;
		return NULL;
		}
}
namespace sttSav
{
  void PlanetaryFaceUVArchiveDictionary::insertLookup (node * n)
                                   {
		reserveIds(n->aid.value-1);
		mLookup[n->aid.value-1].ptr = n;
		}
}
namespace sttSav
{
  void PlanetaryFaceUVArchiveDictionary::clearLookup (archiveId const aid)
                                              {
		if (aid.value && aid.value < mLookup.size())
			mLookup[aid.value-1].ptr = NULL;
		}
}
namespace sttSav
{
  PlanetaryFaceUVArchiveDictionary::node * PlanetaryFaceUVArchiveDictionary::lookup (node * start, unpackedKey const & key)
                                                                 {
		node* current = start;
		while (current) {
			node* exact = NULL;
			node* remainder = NULL;
			
			if (!current->children.size())
				return current;
			for (node* child : current->children) {
				if (child->containsExact(key)) {
					exact = child;
					break;
					}
				else if (child->isRemainder())
					remainder = child;
				}
			if (exact)
				current = exact;
			else if (remainder)
				current = remainder;
			else
				return current;
			}
		return NULL;
		}
}
namespace sttSav
{
  void PlanetaryFaceUVArchiveDictionary::getArchiveFilename (archiveId const id, char * nameOut, uint32_t & lenOut, uint32_t const maxLen) const
                                                                                                                  {
		node* n = getNodeByArchiveId(id);
		switch (n->type) {
			case PUVADictConstants::NODE_TYPE_PLANET_REMAINDER: 
				lenOut = snprintf(nameOut, maxLen, "planet-r.sav");
				return;
			case PUVADictConstants::NODE_TYPE_PLANET: 
				lenOut = snprintf(nameOut, maxLen, "planet-%i.sav", (int)n->planet);
				return;
			case PUVADictConstants::NODE_TYPE_FACE: 
				{
				if (n->face == PUVADictConstants::GLOBAL_FACE)
					lenOut = snprintf(nameOut, maxLen, "planet-%i-face-g.sav", (int)n->planet);
				else
					lenOut = snprintf(nameOut, maxLen, "planet-%i-face-%i.sav", (int)n->planet, (int)n->face);
				}
				return;
			case PUVADictConstants::NODE_TYPE_LEAF: 
				{
				lenOut = snprintf(nameOut, maxLen, "planet-%i-face-%i-sz%i-u%i-v%i.sav", (int)n->planet, (int)n->face, n->uvSize, n->u, n->v);
				}
				return;
			default:
				STTSAV_ASSERT(false);
			}
		}
}
namespace sttSav
{
  bool PlanetaryFaceUVArchiveDictionary::splitArchive (archiveId const id, STTSAV_VECTOR <recordInfo> const & records, uint32_t const maxArchiveSize, splitResult * resultsOut, uint32_t & numResultsOut, uint32_t const maxResultsOut)
                                                                                                                                                                                                       {
		numResultsOut = 0;

		node* n = getNodeByArchiveId(id);
		if (!n)
			return false;

		if (!n->canSplit())
			return false;

		//////////////////////////////////////////////////////////////////////////
		// Build buckets
		//////////////////////////////////////////////////////////////////////////

		STTSAV_VECTOR<splitBucket> buckets;

		for (const recordInfo& r : records) {
			unpackedKey k(r.key);
			uint32_t bucket = 0;

			switch (n->type) {
				case PUVADictConstants::NODE_TYPE_PLANET_REMAINDER:
					bucket = k.planet;
					break;
				case PUVADictConstants::NODE_TYPE_PLANET:
					bucket = k.face;
					break;
				case PUVADictConstants::NODE_TYPE_FACE:
				case PUVADictConstants::NODE_TYPE_LEAF: {
					const uint32_t parentSize = (n->uvSize == 0) ? PUVADictConstants::ROOT_UV_SIZE : n->uvSize;
					const uint32_t half = parentSize >> 1;
					if (k.localU >= n->u + half)
						bucket |= 1;
					if (k.localV >= n->v + half)
						bucket |= 2;
					break;
					}
				default:
					STTSAV_ASSERT(false);
					return false;
				}

			splitBucket::appendOrInsert(buckets, bucket, r.length);
			}

		//////////////////////////////////////////////////////////////////////////
		// PLANET-R : peel planets.
		//////////////////////////////////////////////////////////////////////////

		if (n->type == PUVADictConstants::NODE_TYPE_PLANET_REMAINDER) {
			std::sort(buckets.rbegin(), buckets.rend());

			uint32_t remaining = 0;
			for (const splitBucket& b : buckets)
				remaining += b.bytes;

			for (const splitBucket& b : buckets) {
				if (remaining <= maxArchiveSize)
					break;

				remaining -= b.bytes;

				node* child = STTSAV_NEW(node);
				child->parent = n->parent;
				child->type = PUVADictConstants::NODE_TYPE_PLANET;
				child->planet = (uint16_t)b.value;
				child->aid = getNextId();

				insertLookup(child);

				n->parent->children.push_back(child);

				STTSAV_ASSERT(numResultsOut < maxResultsOut);

				resultsOut[numResultsOut].aid = child->aid;
				resultsOut[numResultsOut].size = b.bytes;
				++numResultsOut;
				}

			resultsOut[numResultsOut].aid = n->aid;
			resultsOut[numResultsOut].size = remaining;
			++numResultsOut;

			return true;
			}

		//////////////////////////////////////////////////////////////////////////
		// Split this archive into deterministic children.
		//////////////////////////////////////////////////////////////////////////

		clearLookup(n->aid);
		n->aid.value = 0;

		switch (n->type) {
			case PUVADictConstants::NODE_TYPE_PLANET:
				for (uint32_t face = 0;  face <= PUVADictConstants::GLOBAL_FACE;  ++face) {
					node* child = STTSAV_NEW(node);
					child->parent = n;
					child->type = PUVADictConstants::NODE_TYPE_FACE;
					child->planet = n->planet;
					child->face = (uint8_t)face;
					child->flags = n->flags;
					child->aid = getNextId();
					insertLookup(child);
					n->children.push_back(child);
					resultsOut[numResultsOut].aid = child->aid;
					resultsOut[numResultsOut].size = 0;
					++numResultsOut;
					}
				break;

			case PUVADictConstants::NODE_TYPE_FACE:
			case PUVADictConstants::NODE_TYPE_LEAF: {
				const uint8_t parentSize = (n->uvSize == 0) ? PUVADictConstants::ROOT_UV_SIZE : n->uvSize;
				const uint8_t half = parentSize >> 1;

				for (uint32_t q = 0; q < 4; ++q) {
					node* child = STTSAV_NEW(node);
					child->parent = n;
					child->type = PUVADictConstants::NODE_TYPE_LEAF;
					child->planet = n->planet;
					child->face = n->face;
					child->flags = n->flags;
					child->u = n->u;
					child->v = n->v;
					child->uvSize = half;

					if (q & 1)
						child->u += half;
					if (q & 2)
						child->v += half;

					child->aid = getNextId();
					insertLookup(child);
					n->children.push_back(child);
					resultsOut[numResultsOut].aid = child->aid;
					resultsOut[numResultsOut].size = 0;
					++numResultsOut;
					}

				break;
				}

			default:
				STTSAV_ASSERT(false);
				return false;
			}

		//////////////////////////////////////////////////////////////////////////
		// Populate child sizes.
		for (const splitBucket& b : buckets) {
			switch (n->type) {
			case PUVADictConstants::NODE_TYPE_PLANET:
				resultsOut[b.value].size = b.bytes;
				break;
			case PUVADictConstants::NODE_TYPE_FACE:
			case PUVADictConstants::NODE_TYPE_LEAF:
				resultsOut[b.value].size = b.bytes;
				break;
			default:
				break;
				}
			}

		return true;
		}
}
namespace sttSav
{
  bool PlanetaryFaceUVArchiveDictionary::getMergeCandidates (archiveId const id, archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut) const
                                                                                                                                            {
		numArchivesOut = 0;
		node* n = getNodeByArchiveId(id);
		if (!n)
			return false;
		node* parent = n->parent;
		if (!parent)
			return false;

		// Parent must be a routing node.
		if (parent->aid.value != 0)
			return false;
			
		// Root and PLANET-R are never merged.
		if (parent->type == PUVADictConstants::NODE_TYPE_ROOT || parent->type == PUVADictConstants::NODE_TYPE_PLANET_REMAINDER)
			return false;

		for (const node* child : parent->children) {
			if (!child->aid.value)
				return false; // malformed routing node
			STTSAV_ASSERT(numArchivesOut < maxArchivesOut);
			archivesOut[numArchivesOut++] = child->aid;
			}
		return numArchivesOut != 0;
		}
}
namespace sttSav
{
  bool PlanetaryFaceUVArchiveDictionary::mergeArchives (archiveId const * archives, uint32_t const numArchives)
                                                                                  {
		if (!numArchives)
			return false;

		node* first = getNodeByArchiveId(archives[0]);
		if (!first)
			return false;
		node* parent = first->parent;
		if (!parent)
			return false;

		// Parent must currently be routing.
		STTSAV_ASSERT(parent->aid.value == 0);

		// Verify every archive belongs to this parent.
		for (uint32_t i = 0; i < numArchives; ++i) {
			node* n = getNodeByArchiveId(archives[i]);
			if (!n)
				return false;
			if (n->parent != parent)
				return false;
			}

		// Delete every child.
		while (!parent->children.empty()) {
			node* child = parent->children.back();
			parent->children.pop_back();
			clearLookup(child->aid);
			STTSAV_DEL(child, sizeof(node));
			}
		// Parent becomes an archive again.
		parent->aid = getNextId();
		insertLookup(parent);
		return true;
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_planetaryFaceUVArchiveDictionary
#endif //STT_SAV_IMPL_IMPL
