#ifdef STT_SAV_IMPL
#undef STT_SAV_IMPL
#define STT_SAV_CURRENT_FILE __FILE__
#include STT_SAV_CURRENT_FILE
#define STT_SAV_IMPL
#endif
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// sttSav.hh
//

#ifndef LZZ_sttSav_hh
#define LZZ_sttSav_hh
#include <cstdint>
// Header file
#ifndef STTSAV_STRING
	#include <string>
	#define STTSAV_STRING std::string
#endif
#ifndef STTSAV_VECTOR
	#include <vector>
	#define STTSAV_VECTOR std::vector
#endif
#ifndef STTSAV_ASSERT
	#include <cassert>
	#define STTSAV_ASSERT assert
#endif
#ifndef STTSAV_NEW
	#define STTSAV_NEW(X) new X
#endif
#ifndef STTSAV_DEL
	#define STTSAV_DEL(X,SZ) delete X 
#endif
#ifndef STTSAV_NEW_ARR
	#define STTSAV_NEW_ARR(X, SZ) new X[SZ];
#endif
#ifndef STTSAV_DEL_ARR
	#define STTSAV_DEL_ARR(X, SZ) delete[] X;
#endif

namespace sttSav {
struct archiveId { uint32_t value; };
struct recordId  { uint32_t value; };
struct archiveKey { uint32_t value; };

struct recordInfo {
	archiveKey key;
	recordId record;
	uint32_t offset;
	uint32_t length;
	
	struct compareRecords {
		inline bool operator()(const recordInfo& a, const recordInfo& b) const { return a.record.value < b.record.value; };
		inline bool operator()(const recordInfo& a, const recordId& r) const  { return a.record.value < r.value; };
		inline bool operator()(const recordId& r, const recordInfo& b) const { return r.value < b.record.value; };
		};
	};
	
struct splitResult {
    archiveId aid;
    uint32_t size;
	};


class ArchiveDictionaryI {
public:
	/// Archive dictionary interface
	///
	/// An ArchiveDictionaryI maps application-defined archive keys to archive IDs.
	/// The dictionary is responsible for generating archive keys and determining
	/// which archive owns a particular key. It contains no file I/O logic and is
	/// independent of the archive storage format.
	///
	/// Different applications may implement different dictionary strategies
	/// (planetary quadtree, fixed grid, hash table, etc.)
	
	inline ArchiveDictionaryI() {}
	virtual ~ArchiveDictionaryI() {}
	
	//archiveKey buildKey(...) // <-- you should have some kind of buildKey function per dictionary
	virtual archiveId getArchiveId(const archiveKey key) const = 0;
	
	// Fast lookup of archives from a shortlist produced with splitArchive. Falls back to getArchiveId
	virtual archiveId getArchiveIdFromShortlist(const archiveKey key, const splitResult* resultsIn, const uint32_t numResults) const { return getArchiveId(key); }
	
	// Returns a name of an archive
	virtual void getArchiveFilename(const archiveId id, char* nameOut, uint32_t& lenOut, const uint32_t maxLen) const {
		lenOut = snprintf(nameOut, maxLen, "archive%i.sav", (int) id.value);
		}
	
	// Splits an archive into 
	// RETURNS
	// - a list of children archives that should hold all of the records within archiveId id. This may or may not contain archiveId
	// - numChildrenOut - the number of children returned
	// - splitInfoOut - the kind of split that was perfomed. You can use getArchiveIdFromShortlist with this value to accelerte lookup of archives from keys 
	// bool - if a split happened or not
	virtual bool splitArchive(const archiveId id, const STTSAV_VECTOR<recordInfo>& records, const uint32_t maxArchiveSize, splitResult* resultsOut, uint32_t& numResultsOut, const uint32_t maxChildrenOut) = 0;
	
	// For a given archive determine what other archives can be combined according to this dictionary's topology
	// Returns false if there is no legal merge possible
	virtual bool getMergeCandidates(const archiveId id, archiveId* archivesOut, uint32_t& numArchivesOut, const uint32_t maxArchivesOut) const = 0;
	
	// Commits the merge in the dictionary, from the list provided by getMergeCandidates
	virtual bool mergeArchives(const archiveId* archives, const uint32_t numArchives) = 0;
	
	// Returns the total number of archives in the dictionary. Set "archivesOut" to NULL to just query. numArchivesOut is the number of archives written to the archivesOut array
	virtual uint32_t extractArchiveIds(archiveId* archivesOut, uint32_t& numArchivesOut, const uint32_t maxArchivesOut) const = 0;
	
	// Serialises this dictionary for disc storage
	virtual STTSAV_STRING encodeDictionary() const = 0;
	
	// Decodes and initialises this dictionary. Returns the number of archives in the directory 
	virtual uint32_t decodeDictionary(const STTSAV_STRING& data) = 0;
	
	// printf's to stdout this dictonary
	virtual void dbgDump() const {}
	};

struct transactionMode {
	constexpr static uint8_t TM_UNKOWN = 0;
	constexpr static uint8_t TM_LOAD = 1;
	constexpr static uint8_t TM_SAVE = 2;
	constexpr static uint8_t TM_DELETE  = 3;
	constexpr static uint8_t TM_COMPACT = 4;
	constexpr static uint8_t TM_SPLIT = 5;
	constexpr static uint8_t TM_JOIN  = 6;
	constexpr static uint8_t TM_count  = 7;
	};
} // namespace sttSav
#define LZZ_INLINE inline
namespace sttSav
{
  struct buffer
  {
    uint8_t const * data;
    uint32_t len;
    buffer ();
    buffer (char const * _buff, uint32_t const _len);
  };
}
namespace sttSav
{
  struct transaction
  {
    archiveKey mKey;
    recordId mRecord;
    uint8_t mode;
    buffer mBufferOut;
    STTSAV_STRING * stringOut;
    bool forceOperation;
    bool success;
    void initToZero ();
    static transaction makeLoad (archiveKey const _mKey, recordId const _mRecord, STTSAV_STRING & out);
    static transaction makeSave (archiveKey const _mKey, recordId const _mRecord, char const * buff, uint32_t const len);
    static transaction makeSave (archiveKey const _mKey, recordId const _mRecord, buffer const _buff);
    static transaction makeDelete (archiveKey const _mKey, recordId const _mRecord);
    static transaction makeCompact (archiveKey const _mKey, bool const forceCompact);
    static transaction makeSplit (archiveKey const _mKey, bool const forceSplit);
    static transaction makeJoin (archiveKey const _mKey, bool const forceJoin);
  };
}
namespace sttSav
{
  struct recordHeaderShort
  {
    recordId id;
    uint32_t offset;
  };
}
namespace sttSav
{
  LZZ_INLINE buffer::buffer ()
                        {}
}
namespace sttSav
{
  LZZ_INLINE buffer::buffer (char const * _buff, uint32_t const _len)
    : data ((const uint8_t*)_buff), len (_len)
                                                                                                       {}
}
namespace sttSav
{
  LZZ_INLINE void transaction::initToZero ()
                                 {
		mKey.value = 0;
		mRecord.value = 0;
		mode = transactionMode::TM_UNKOWN;
		mBufferOut.data = 0;
		mBufferOut.len = 0;
		stringOut = NULL;
		forceOperation = false;
		success = false;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeLoad (archiveKey const _mKey, recordId const _mRecord, STTSAV_STRING & out)
                                                                                                                {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mRecord = _mRecord;
		r.mode = transactionMode::TM_LOAD;
		r.stringOut = &out;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeSave (archiveKey const _mKey, recordId const _mRecord, char const * buff, uint32_t const len)
                                                                                                                                  {
		return makeSave(_mKey, _mRecord, buffer(buff, len));
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeSave (archiveKey const _mKey, recordId const _mRecord, buffer const _buff)
                                                                                                                {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mRecord = _mRecord;
		r.mode = transactionMode::TM_SAVE;
		r.mBufferOut = _buff;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeDelete (archiveKey const _mKey, recordId const _mRecord)
                                                                                              {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mRecord = _mRecord;
		r.mode = transactionMode::TM_DELETE;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeCompact (archiveKey const _mKey, bool const forceCompact)
                                                                                               {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mode = transactionMode::TM_COMPACT;
		r.forceOperation = forceCompact;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeSplit (archiveKey const _mKey, bool const forceSplit)
                                                                                           {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mode = transactionMode::TM_SPLIT;
		r.forceOperation = forceSplit;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeJoin (archiveKey const _mKey, bool const forceJoin)
                                                                                         {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mode = transactionMode::TM_JOIN;
		r.forceOperation = forceJoin;
		return r;
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_sttSav
#define STT_SAV_IMPL_DOUBLE_GUARD_sttSav
#define LZZ_OVERRIDE
// sttSav.cpp
//

// Implmentation file
#include <algorithm>
#define LZZ_INLINE inline
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_sttSav
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// fileHandle.hh
//

#ifndef LZZ_fileHandle_hh
#define LZZ_fileHandle_hh
#include <stdio.h>
#define LZZ_INLINE inline
namespace sttSav
{
  struct FileOps
  {
    static bool exists (char const * filename);
    static bool move (char const * filenameOld, char const * filenameNew);
    static bool remove (char const * filename);
    static bool replace (char const * filenameOld, char const * filenameNew);
    static bool deleteFile (char const * filename);
  };
}
namespace sttSav
{
  class FileHandle
  {
  public:
    enum openMode
    {
      OM_CLOSED = 0,
      OM_READ,
      OM_READ_WRITE
    };
  private:
    FILE * mFile;
    openMode mMode;
  public:
    FileHandle ();
    ~ FileHandle ();
    bool isOpen () const;
    openMode getMode () const;
    bool openRead (char const * filename);
    bool openReadWrite (char const * filename, bool const createIfMissing = true);
    bool truncateAndReopen (char const * filename);
    void close ();
    bool flush ();
    bool seek (uint64_t const offset);
    uint64_t tell () const;
    uint64_t length ();
    bool read (void * dst, uint32_t const len);
    bool write (void const * src, uint32_t const len);
    template <typename T>
    bool read (T & value);
    template <typename T>
    bool write (T const & value);
    template <typename T>
    bool writeArray (T const * data, uint32_t count);
    template <typename T>
    bool readArray (T * dst, uint32_t const count);
    bool truncate (uint64_t const newLength);
    static bool copyRange_worker (FileHandle & src, uint64_t const srcOffset, uint32_t const len, FileHandle & dst, char * workingBuff);
    static bool copyRange (FileHandle & src, uint64_t const srcOffset, uint32_t const len, FileHandle & dst);
  };
}
namespace sttSav
{
  template <typename T>
  bool FileHandle::read (T & value)
                            {
		return read(&value, sizeof(T));
		}
}
namespace sttSav
{
  template <typename T>
  bool FileHandle::write (T const & value)
                                   {
		return write(&value, sizeof(T));
		}
}
namespace sttSav
{
  template <typename T>
  bool FileHandle::writeArray (T const * data, uint32_t count)
                                                       {
		if (!count) return true;
		STTSAV_ASSERT(std::is_trivially_copyable<T>::value);
		return write(data, count * sizeof(T));
		}
}
namespace sttSav
{
  template <typename T>
  bool FileHandle::readArray (T * dst, uint32_t const count)
                                                     {
		if (!count) return true;
		STTSAV_ASSERT(std::is_trivially_copyable<T>::value);
		return read(dst, count * sizeof(T));
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_fileHandle
#define STT_SAV_IMPL_DOUBLE_GUARD_fileHandle
#define LZZ_OVERRIDE
// fileHandle.cpp
//

#include <cstdio>
#include <cstdint>

#ifdef _WIN32
	#include <io.h>
#else
	#include <unistd.h>
#endif
#define LZZ_INLINE inline
namespace sttSav
{
  bool FileOps::exists (char const * filename)
                                                 {
		#ifdef _WIN32
			return _access(filename, 0) == 0;
		#else
			return access(filename, F_OK) == 0;
		#endif
		}
}
namespace sttSav
{
  bool FileOps::move (char const * filenameOld, char const * filenameNew)
                                                                           {
		return ::rename(filenameOld, filenameNew) == 0;
		}
}
namespace sttSav
{
  bool FileOps::remove (char const * filename)
                                                 {
		return ::remove(filename) == 0;
		}
}
namespace sttSav
{
  bool FileOps::replace (char const * filenameOld, char const * filenameNew)
                                                                              {
		#ifdef _WIN32
			return MoveFileExA(filenameOld, filenameNew, MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH) != 0;
		#else
			return ::rename(filenameOld, filenameNew) == 0;
		#endif
		}
}
namespace sttSav
{
  bool FileOps::deleteFile (char const * filename)
                                                     {
		return ::remove(filename) == 0;
		}
}
namespace sttSav
{
  FileHandle::FileHandle ()
    : mFile (NULL), mMode (OM_CLOSED)
                                                     {}
}
namespace sttSav
{
  FileHandle::~ FileHandle ()
                      {
		close();
		}
}
namespace sttSav
{
  bool FileHandle::isOpen () const
                            {
		return mFile != NULL;
		}
}
namespace sttSav
{
  FileHandle::openMode FileHandle::getMode () const
                                 {
		return mMode;
		}
}
namespace sttSav
{
  bool FileHandle::openRead (char const * filename)
                                            {
		close();
		mFile = fopen(filename, "rb");
		if (!mFile)
			return false;
		mMode = OM_READ;
		return true;
		}
}
namespace sttSav
{
  bool FileHandle::openReadWrite (char const * filename, bool const createIfMissing)
                                                                                    {
		close();

		// Try opening existing file first.
		mFile = fopen(filename, "rb+");
		if (!mFile && createIfMissing)
			mFile = fopen(filename, "wb+");
			
		if (!mFile)
			return false;
		mMode = OM_READ_WRITE;
		return true;
		}
}
namespace sttSav
{
  bool FileHandle::truncateAndReopen (char const * filename)
                                                     {
		if (isOpen()) close();
		mFile = fopen(filename, "wb+");
		
		if (!mFile)
			return false;
		mMode = OM_READ_WRITE;
		return true;
		}
}
namespace sttSav
{
  void FileHandle::close ()
                     {
		if (mFile) {
			fclose(mFile);
			mFile = NULL;
			}
		mMode = OM_CLOSED;
		}
}
namespace sttSav
{
  bool FileHandle::flush ()
                     {
		if (!mFile)
			return false;
		return fflush(mFile) == 0;
		}
}
namespace sttSav
{
  bool FileHandle::seek (uint64_t const offset)
                                         {
		if (!mFile)
			return false;
#ifdef _WIN32
		return _fseeki64(mFile, (__int64)offset, SEEK_SET) == 0;
#else
		return fseeko(mFile, (off_t)offset, SEEK_SET) == 0;
#endif
		}
}
namespace sttSav
{
  uint64_t FileHandle::tell () const
                              {
		if (!mFile)
			return 0;
#ifdef _WIN32
		return (uint64_t)_ftelli64(mFile);
#else
		return (uint64_t)ftello(mFile);
#endif
		}
}
namespace sttSav
{
  uint64_t FileHandle::length ()
                          {
		if (!mFile)
			return 0;

		uint64_t oldPos = tell();
#ifdef _WIN32
		_fseeki64(mFile, 0, SEEK_END);
		uint64_t len = (uint64_t)_ftelli64(mFile);
		_fseeki64(mFile, (__int64)oldPos, SEEK_SET);
#else
		fseeko(mFile, 0, SEEK_END);
		uint64_t len = (uint64_t)ftello(mFile);
		fseeko(mFile, (off_t)oldPos, SEEK_SET);
#endif
		return len;
		}
}
namespace sttSav
{
  bool FileHandle::read (void * dst, uint32_t const len)
                                                 {
		if (!mFile)
			return false;
		return fread(dst, 1, len, mFile) == len;
		}
}
namespace sttSav
{
  bool FileHandle::write (void const * src, uint32_t const len)
                                                        {
		if (!mFile)
			return false;
		return fwrite(src, 1, len, mFile) == len;
		}
}
namespace sttSav
{
  bool FileHandle::truncate (uint64_t const newLength)
                                                {
		if (!mFile)
			return false;

		flush();
#ifdef _WIN32
		return _chsize_s(_fileno(mFile), newLength) == 0;
#else
		return ftruncate(fileno(mFile), (off_t)newLength) == 0;
#endif
		}
}
namespace sttSav
{
  bool FileHandle::copyRange_worker (FileHandle & src, uint64_t const srcOffset, uint32_t const len, FileHandle & dst, char * workingBuff)
                                                                                                                                        {
		// workingBuff must be big enough to hold
		if (!src.read(workingBuff, len))
			return false;
		if (!dst.write(workingBuff, len))
			return false;
		if (!src.seek(srcOffset))
			return false;
		return true;
		}
}
namespace sttSav
{
  bool FileHandle::copyRange (FileHandle & src, uint64_t const srcOffset, uint32_t const len, FileHandle & dst)
                                                                                                              {
		// Copies a block from src to dst, appending dst
		constexpr uint32_t BUFFER_SIZE = 64 * 1024;
		char buff_mem[BUFFER_SIZE];
		char* buff = &buff_mem[0];
		
		bool hasAlloced = false;
		if (len+1 >= BUFFER_SIZE) {
			buff = STTSAV_NEW_ARR(char, len+1);
			hasAlloced = true;
			}
		
		bool r = copyRange_worker(src, srcOffset, len, dst, buff);
		
		if (hasAlloced)
			STTSAV_DEL_ARR(buff, BUFFER_SIZE+1);
		return r;
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_fileHandle
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// splitBucket.hh
//

#ifndef LZZ_splitBucket_hh
#define LZZ_splitBucket_hh
#define LZZ_INLINE inline
namespace sttSav
{
  struct splitBucket
  {
    uint32_t value;
    uint32_t bytes;
    splitBucket ();
    splitBucket (uint32_t const _value, uint32_t const _bytes);
    bool operator < (splitBucket const & other) const;
    static void appendOrInsert (STTSAV_VECTOR <splitBucket> & buckets, uint32_t const _value, uint32_t const _bytes);
  };
}
namespace sttSav
{
  LZZ_INLINE splitBucket::splitBucket ()
                             { value = 0; bytes = 0; }
}
namespace sttSav
{
  LZZ_INLINE splitBucket::splitBucket (uint32_t const _value, uint32_t const _bytes)
                                                                         { value = _value; bytes = _bytes; }
}
namespace sttSav
{
  LZZ_INLINE bool splitBucket::operator < (splitBucket const & other) const
                                                                 { return bytes < other.bytes; }
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_splitBucket
#define STT_SAV_IMPL_DOUBLE_GUARD_splitBucket
#define LZZ_OVERRIDE
// splitBucket.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  void splitBucket::appendOrInsert (STTSAV_VECTOR <splitBucket> & buckets, uint32_t const _value, uint32_t const _bytes)
                                                                                                                      {
		for (splitBucket& b : buckets) {
			if (b.value == _value) {
				b.bytes += _bytes;
				return;
				}
			}
		buckets.push_back(splitBucket(_value, _bytes));
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_splitBucket
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// dictionaryLookup.hh
//

#ifndef LZZ_dictionaryLookup_hh
#define LZZ_dictionaryLookup_hh
#define LZZ_INLINE inline
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  class DictionaryLookup
  {
  public:
    struct nodeLookup
    {
      archiveId aid;
      NODE * ptr;
    };
    STTSAV_VECTOR <nodeLookup> mLookup;
    void reserveIds (uint32_t const numIds);
    void rebuildLookupArray (NODE * root);
    void rebuildLookupArrayWorker (NODE * working);
    archiveId getNextId ();
    archiveId getArchiveId (archiveKey const key, NODE * root) const;
    NODE * getNodeByArchiveId (archiveId const aid) const;
    void insertLookup (NODE * n);
    void clearLookup (archiveId const aid);
    static NODE * lookup (NODE * start, UNPACKED_KEY const & key);
    void extractArchiveIdsWorker (uint32_t & workingCount, archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut) const;
  };
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  class DictionaryMergeHelper
  {
  public:
    static bool getMergeCandidatesWorker (DictionaryLookup <NODE,UNPACKED_KEY> const & mLookup, archiveId const id, archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut);
    static bool mergeArchivesWorker (DictionaryLookup <NODE,UNPACKED_KEY> & mLookup, archiveId const * archives, uint32_t const numArchives);
  };
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  void DictionaryLookup <NODE, UNPACKED_KEY>::reserveIds (uint32_t const numIds)
                                               {
		if (numIds <= mLookup.size()) return;
		uint32_t start = mLookup.size();
		mLookup.resize(numIds);
		for (uint32_t i = start; i < numIds; ++i) {
			mLookup[i].aid.value = i + 1;
			mLookup[i].ptr = NULL;
			}
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  void DictionaryLookup <NODE, UNPACKED_KEY>::rebuildLookupArray (NODE * root)
                                            {
		mLookup.clear();
		rebuildLookupArrayWorker(root);
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  void DictionaryLookup <NODE, UNPACKED_KEY>::rebuildLookupArrayWorker (NODE * working)
                                                     {
		insertLookup(working);
		for (NODE* c : working->children)
			rebuildLookupArrayWorker(c);
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  archiveId DictionaryLookup <NODE, UNPACKED_KEY>::getNextId ()
                              {
		for (uint32_t i = 0; i < mLookup.size(); ++i) {
			if (mLookup[i].ptr == NULL)
				return mLookup[i].aid;
			}
		// all slots are full
		nodeLookup l;
		l.aid.value = mLookup.size()+1;
		l.ptr = NULL;
		mLookup.push_back(l);
		return l.aid;
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  archiveId DictionaryLookup <NODE, UNPACKED_KEY>::getArchiveId (archiveKey const key, NODE * root) const
                                                                       {
		// Searches the entire tree for an archive for a specified key
		NODE* n = lookup(root, key);
		if (n)
			return n->aid;
		return {0};
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  NODE * DictionaryLookup <NODE, UNPACKED_KEY>::getNodeByArchiveId (archiveId const aid) const
                                                             {
		if (aid.value && aid.value-1 < mLookup.size())
			return mLookup[aid.value-1].ptr;
		return NULL;
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  void DictionaryLookup <NODE, UNPACKED_KEY>::insertLookup (NODE * n)
                                   {
		reserveIds(n->aid.value-1);
		mLookup[n->aid.value-1].ptr = n;
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  void DictionaryLookup <NODE, UNPACKED_KEY>::clearLookup (archiveId const aid)
                                              {
		if (aid.value && aid.value < mLookup.size())
			mLookup[aid.value-1].ptr = NULL;
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  NODE * DictionaryLookup <NODE, UNPACKED_KEY>::lookup (NODE * start, UNPACKED_KEY const & key)
                                                                  {
		NODE* current = start;
		while (current) {
			NODE* exact = NULL;
			NODE* remainder = NULL;
			
			if (!current->children.size())
				return current;
			for (NODE* child : current->children) {
				if (child->containsExact(key)) {
					exact = child;
					break;
					}
				else if (child->isRemainder())
					remainder = child;
				}
			if (exact)
				current = exact;
			else if (remainder)
				current = remainder;
			else
				return current;
			}
		return NULL;
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  void DictionaryLookup <NODE, UNPACKED_KEY>::extractArchiveIdsWorker (uint32_t & workingCount, archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut) const
                                                                                                                                                    {
		for (uint32_t i = 0; i < mLookup.size(); ++i) {
			if (mLookup[i].aid.value) {
				if (archivesOut && numArchivesOut < maxArchivesOut) {
					archivesOut[numArchivesOut] = mLookup[i].aid;
					numArchivesOut++;
					}
				workingCount++;
				}
			}
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  bool DictionaryMergeHelper <NODE, UNPACKED_KEY>::getMergeCandidatesWorker (DictionaryLookup <NODE,UNPACKED_KEY> const & mLookup, archiveId const id, archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut)
                                                                                                                                                                                                      {
		numArchivesOut = 0;
		NODE* n = mLookup.getNodeByArchiveId(id);
		if (!n)
			return false;
		NODE* parent = n->parent;
		if (!parent)
			return false;

		// Parent must be a routing node.
		if (parent->aid.value != 0)
			return false;
			
		// Root and PLANET-R are never merged.
		if (!n->isAllowedToMerge())
			return false;
			
		for (const NODE* child : parent->children) {
			if (!child->aid.value)
				return false; // malformed routing node
			STTSAV_ASSERT(numArchivesOut < maxArchivesOut);
			archivesOut[numArchivesOut++] = child->aid;
			}
		return numArchivesOut != 0;
		}
}
namespace sttSav
{
  template <typename NODE, typename UNPACKED_KEY>
  bool DictionaryMergeHelper <NODE, UNPACKED_KEY>::mergeArchivesWorker (DictionaryLookup <NODE,UNPACKED_KEY> & mLookup, archiveId const * archives, uint32_t const numArchives)
                                                                                                                                             {
		if (!numArchives)
			return false;

		NODE* first = mLookup.getNodeByArchiveId(archives[0]);
		if (!first)
			return false;
		NODE* parent = first->parent;
		if (!parent)
			return false;

		// Parent must currently be routing.
		STTSAV_ASSERT(parent->aid.value == 0);

		// Verify every archive belongs to this parent.
		for (uint32_t i = 0; i < numArchives; ++i) {
			NODE* n = mLookup.getNodeByArchiveId(archives[i]);
			if (!n)
				return false;
			if (n->parent != parent)
				return false;
			}

		// Delete every child.
		while (!parent->children.empty()) {
			NODE* child = parent->children.back();
			parent->children.pop_back();
			mLookup.clearLookup(child->aid);
			STTSAV_DEL(child, sizeof(NODE));
			}
		// Parent becomes an archive again.
		parent->aid = mLookup.getNextId();
		mLookup.insertLookup(parent);
		return true;
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_dictionaryLookup
#define STT_SAV_IMPL_DOUBLE_GUARD_dictionaryLookup
#define LZZ_OVERRIDE
// dictionaryLookup.cpp
//

// empty .cpp file
#define LZZ_INLINE inline
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_dictionaryLookup
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// stringEncoder.hh
//

#ifndef LZZ_stringEncoder_hh
#define LZZ_stringEncoder_hh
#define LZZ_INLINE inline
namespace sttSav
{
  class StringEncoder
  {
  public:
    STTSAV_STRING & buff;
    StringEncoder (STTSAV_STRING & storage);
    void reserve (uint32_t const initialCapacity);
    uint64_t getSeek () const;
    template <typename T>
    void parse (T const & t);
    template <typename T>
    void parseAt (uint64_t const offset, T const & value);
    void parseSize (uint64_t const trueSize);
    void parseString (STTSAV_STRING const & str);
    void parseString (char const * str, uint32_t const sz);
  };
}
namespace sttSav
{
  class StringDecoder
  {
  public:
    STTSAV_STRING const & buff;
    uint64_t seek;
    bool hasError;
    StringDecoder (STTSAV_STRING const & _src);
    bool isOk () const;
    void onBufferOverflow (uint64_t const read);
    bool checkError2 (uint64_t const read);
    template <typename T>
    void parse (T & tout);
    template <typename T>
    T parse ();
    template <typename T>
    void parseAt (uint64_t offset, T & tout) const;
    void parseString (STTSAV_STRING & out);
    uint64_t parseSize ();
  };
}
namespace sttSav
{
  LZZ_INLINE StringEncoder::StringEncoder (STTSAV_STRING & storage)
    : buff (storage)
                                                                     {}
}
namespace sttSav
{
  LZZ_INLINE void StringEncoder::reserve (uint32_t const initialCapacity)
                                                            {
		buff.reserve(initialCapacity);
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t StringEncoder::getSeek () const
                                        { return buff.size(); }
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringEncoder::parse (T const & t)
                                       {
		buff += std::string_view((char*)&t, sizeof(T));
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringEncoder::parseAt (uint64_t const offset, T const & value)
                                                                   {
		memcpy(&buff[offset], &value, sizeof(T));
		}
}
namespace sttSav
{
  LZZ_INLINE void StringEncoder::parseSize (uint64_t const trueSize)
                                                       {
		if (trueSize >= uint8_t(-1)) {
			parse<uint8_t>(-1);
			parse<uint64_t>(trueSize);
			}
		else
			parse<uint8_t>(trueSize);
		}
}
namespace sttSav
{
  LZZ_INLINE StringDecoder::StringDecoder (STTSAV_STRING const & _src)
    : buff (_src), seek (0), hasError (false)
                                                                                                {}
}
namespace sttSav
{
  LZZ_INLINE bool StringDecoder::isOk () const
                                 { return !hasError; }
}
namespace sttSav
{
  LZZ_INLINE bool StringDecoder::checkError2 (uint64_t const read)
                                                     {
		if (hasError) return true;
		if (read + seek > buff.size()) {
			onBufferOverflow(read);
			hasError = true;
			}
		return hasError;
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringDecoder::parse (T & tout)
                                    {
		if (checkError2(sizeof(T))) return;
		buff.copy((char *) &tout, sizeof(T), seek);
		seek += sizeof(T);
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE T StringDecoder::parse ()
                         {
		if (checkError2(sizeof(T))) return T();
		T tout;
		buff.copy((char *) &tout, sizeof(T), seek);
		seek += sizeof(T);
		return tout;
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringDecoder::parseAt (uint64_t offset, T & tout) const
                                                            {
		buff.copy((char *) &tout, sizeof(T), offset);
		}
}
namespace sttSav
{
  LZZ_INLINE void StringDecoder::parseString (STTSAV_STRING & out)
                                                    {
		uint64_t sz = parseSize();
		seek += sz;
		out = buff.substr(seek-sz, sz);
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t StringDecoder::parseSize ()
                                    {
		uint64_t sz = parse<uint8_t>();
		if (sz == uint8_t(-1))
			sz = parse<uint64_t>();
		return sz;
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#define STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#define LZZ_OVERRIDE
// stringEncoder.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  void StringEncoder::parseString (STTSAV_STRING const & str)
                                                    {
		parseSize(str.size());
		buff += str;
		}
}
namespace sttSav
{
  void StringEncoder::parseString (char const * str, uint32_t const sz)
                                                             {
		parseSize(sz);
		buff += str;
		}
}
namespace sttSav
{
  void StringDecoder::onBufferOverflow (uint64_t const read)
                                                   {
		printf("stt-sav buffer overflow! read %i at %i of string size %i\n", (int)read, (int)seek, (int)buff.size());
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// binaryValueWriter.hh
//

#ifndef LZZ_binaryValueWriter_hh
#define LZZ_binaryValueWriter_hh
namespace sttSav {
struct bvConstants {
	static constexpr uint8_t BV_EMPTY = 0;
	static constexpr uint8_t BV_BOOL = 1;
static constexpr uint8_t BV_NUMBERS_START = 2;
	static constexpr uint8_t BV_FLOAT = 2;
	static constexpr uint8_t BV_DOUBLE = 3;
	static constexpr uint8_t BV_UINT8 = 4;
	static constexpr uint8_t BV_UINT16 = 5;
	static constexpr uint8_t BV_UINT32 = 6;
	static constexpr uint8_t BV_UINT64 = 7;
	static constexpr uint8_t BV_INT8 = 8;
	static constexpr uint8_t BV_INT16 = 9;
	static constexpr uint8_t BV_INT32 = 10;
	static constexpr uint8_t BV_INT64 = 11;
static constexpr uint8_t BV_NUMBERS_END = 11;
	static constexpr uint8_t BV_STRING = 12;
	static constexpr uint8_t BV_OBJECT = 13;
	static constexpr uint8_t BV_ARRAY = 14;
	};
}
#define LZZ_INLINE inline
namespace sttSav
{
  class BinaryValue
  {
  public:
    StringDecoder * dec;
    uint64_t offset;
  public:
    BinaryValue ();
    BinaryValue (StringDecoder * _dec);
  protected:
    uint8_t getBvType () const;
    uint64_t payloadOffset () const;
    uint32_t getJumpSize () const;
    uint32_t getMemberCount () const;
    uint64_t childOffset () const;
    uint64_t nextOffset () const;
    int64_t getInteger () const;
    double getFloating () const;
  public:
    bool IsValid () const;
    bool IsArray () const;
    bool IsObject () const;
    bool IsString () const;
    bool IsBool () const;
    bool IsNumber () const;
    uint32_t Size () const;
    int8_t GetInt8 () const;
    int16_t GetInt16 () const;
    int32_t GetInt32 () const;
    int64_t GetInt64 () const;
    int32_t GetInt () const;
    uint8_t GetUint8 () const;
    uint16_t GetUint16 () const;
    uint32_t GetUint32 () const;
    uint64_t GetUint64 () const;
    uint32_t GetUint () const;
    float GetFloat () const;
    float GetDouble () const;
    bool GetBool () const;
    STTSAV_STRING GetString () const;
    void GetStringRef (STTSAV_STRING & out) const;
    uint32_t GetStringLength () const;
    BinaryValue operator [] (uint32_t index) const;
    BinaryValue operator [] (char const * key) const;
    STTSAV_STRING toDbgString () const;
    STTSAV_STRING toDbgStringIndented (uint32_t indent) const;
  };
}
namespace sttSav
{
  class BinaryWriter
  {
  public:
    StringEncoder * enc;
  protected:
    struct scope
    {
      uint64_t startOffset;
      uint32_t memberCount;
      bool isObject;
    };
    STTSAV_VECTOR <scope> stack;
  public:
    BinaryWriter ();
    BinaryWriter (StringEncoder * _enc);
  protected:
    void onValueWritten ();
    void startContainer (uint8_t const bvType, bool const isObject);
    void endContainer ();
    template <typename T>
    void writePrimitive (uint8_t const bvType, T const value);
  public:
    void StartObject ();
    void StartArray ();
    void EndObject ();
    void EndArray ();
    void Key (char const * str);
    void Int (int const v);
    void Int8 (int8_t const v);
    void Int16 (int16_t const v);
    void Int32 (int32_t const v);
    void Int64 (int64_t const v);
    void Uint (unsigned int const v);
    void Uint8 (uint8_t const v);
    void Uint16 (uint16_t const v);
    void Uint32 (uint32_t const v);
    void Uint64 (uint64_t const v);
    void Float (float const v);
    void Double (double const v);
    void Bool (bool const v);
    void String (char const * str, uint32_t const len);
    void String (char const * str);
    void String (STTSAV_STRING const & str);
  };
}
namespace sttSav
{
  LZZ_INLINE BinaryValue::BinaryValue ()
    : dec (NULL), offset (0)
                                                {}
}
namespace sttSav
{
  LZZ_INLINE BinaryValue::BinaryValue (StringDecoder * _dec)
    : dec (_dec), offset (0)
                                                                  {}
}
namespace sttSav
{
  LZZ_INLINE uint8_t BinaryValue::getBvType () const
                                         {
		return dec->buff[offset];
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::payloadOffset () const
                                              {
		return offset + 1;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::getJumpSize () const
                                            {
		uint32_t v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::getMemberCount () const
                                               {
		uint32_t v;
		dec->parseAt(payloadOffset() + sizeof(uint32_t), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::childOffset () const
                                            {
		return payloadOffset() + sizeof(uint32_t) * 2;
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::nextOffset () const
                                           {
		switch (getBvType()) {
			case bvConstants::BV_BOOL:
			case bvConstants::BV_UINT8:
			case bvConstants::BV_INT8:
				return offset + 2;

			case bvConstants::BV_UINT16:
			case bvConstants::BV_INT16:
				return offset + 3;

			case bvConstants::BV_FLOAT:
			case bvConstants::BV_UINT32:
			case bvConstants::BV_INT32:
				return offset + 5;

			case bvConstants::BV_DOUBLE:
			case bvConstants::BV_UINT64:
			case bvConstants::BV_INT64:
				return offset + 9;

			case bvConstants::BV_STRING: {
				StringDecoder d(*dec);
				d.seek = payloadOffset();
				uint64_t sz = d.parseSize();
				return d.seek + sz;
				}

			case bvConstants::BV_ARRAY:
			case bvConstants::BV_OBJECT:
				return offset + getJumpSize();

			default:
				STTSAV_ASSERT(false);
				return offset;
			}
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsValid () const
                                    { return dec; }
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsArray () const
                                    {
		return getBvType() == bvConstants::BV_ARRAY;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsObject () const
                                     {
		return getBvType() == bvConstants::BV_OBJECT;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsString () const
                                     {
		return getBvType() == bvConstants::BV_STRING;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsBool () const
                                   {
		return getBvType() == bvConstants::BV_BOOL;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsNumber () const
                                     {
		const uint8_t t = getBvType();
		return t >= bvConstants::BV_NUMBERS_START && t <= bvConstants::BV_NUMBERS_END;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::Size () const
                                     {
		return getMemberCount();
		}
}
namespace sttSav
{
  LZZ_INLINE int8_t BinaryValue::GetInt8 () const
                                      { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE int16_t BinaryValue::GetInt16 () const
                                        { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE int32_t BinaryValue::GetInt32 () const
                                        { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE int64_t BinaryValue::GetInt64 () const
                                        { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE int32_t BinaryValue::GetInt () const
                                      { return GetInt32(); }
}
namespace sttSav
{
  LZZ_INLINE uint8_t BinaryValue::GetUint8 () const
                                        { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE uint16_t BinaryValue::GetUint16 () const
                                          { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetUint32 () const
                                          { return getInteger(); }
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::GetUint64 () const
                                          {
		if (getBvType() == bvConstants::BV_UINT64) {
			uint64_t v;
			dec->parseAt(payloadOffset(), v);
			return v;
			}
		return getInteger();
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetUint () const
                                        { return GetUint32(); }
}
namespace sttSav
{
  LZZ_INLINE float BinaryValue::GetFloat () const
                                      { return getFloating(); }
}
namespace sttSav
{
  LZZ_INLINE float BinaryValue::GetDouble () const
                                       { return getFloating(); }
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::GetBool () const
                                    {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsBool());
		uint8_t v;
		dec->parseAt(payloadOffset(), v);
		return v != 0;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetStringLength () const
                                                {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsString());
		StringDecoder d(*dec);
		d.seek = payloadOffset();
		return (uint32_t)d.parseSize();
		}
}
namespace sttSav
{
  LZZ_INLINE BinaryWriter::BinaryWriter ()
    : enc (NULL)
                                          {}
}
namespace sttSav
{
  LZZ_INLINE BinaryWriter::BinaryWriter (StringEncoder * _enc)
    : enc (_enc)
                                                            {}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::onValueWritten ()
                                     {
		if (!stack.empty() && !stack.back().isObject)
			stack.back().memberCount++;
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::startContainer (uint8_t const bvType, bool const isObject)
                                                                              {
		onValueWritten();

		scope s;
		s.startOffset = enc->getSeek();
		s.memberCount = 0;
		s.isObject = isObject;
		stack.push_back(s);

		enc->parse<uint8_t>(bvType);
		enc->parse<uint32_t>(0); // Jump placeholder
		enc->parse<uint32_t>(0); // Member count placeholder
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::endContainer ()
                                   {
		STTSAV_ASSERT(!stack.empty());

		const scope s = stack.back();
		stack.pop_back();

		const uint32_t jump = uint32_t(enc->getSeek() - s.startOffset);

		enc->parseAt<uint32_t>(s.startOffset + 1, jump);
		enc->parseAt<uint32_t>(s.startOffset + 5, s.memberCount);
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void BinaryWriter::writePrimitive (uint8_t const bvType, T const value)
                                                                        {
		onValueWritten();
		enc->parse<uint8_t>(bvType);
		enc->parse<T>(value);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::StartObject ()
                                  {
		startContainer(bvConstants::BV_OBJECT, true);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::StartArray ()
                                 {
		startContainer(bvConstants::BV_ARRAY, false);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::EndObject ()
                                {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(stack.back().isObject);
		endContainer();
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::EndArray ()
                               {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(!stack.back().isObject);
		endContainer();
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Key (char const * str)
                                         {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(stack.back().isObject);
		stack.back().memberCount++;
		enc->parseString(str, strlen(str));
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int (int const v)
                                     { Int32(v); }
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int8 (int8_t const v)
                                         {
		writePrimitive<int8_t>(bvConstants::BV_INT8, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int16 (int16_t const v)
                                           {
		writePrimitive<int16_t>(bvConstants::BV_INT16, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int32 (int32_t const v)
                                           {
		writePrimitive<int32_t>(bvConstants::BV_INT32, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int64 (int64_t const v)
                                           {
		writePrimitive<int64_t>(bvConstants::BV_INT64, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint (unsigned int const v)
                                           { Uint32(v); }
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint8 (uint8_t const v)
                                           {
		writePrimitive<uint8_t>(bvConstants::BV_UINT8, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint16 (uint16_t const v)
                                             {
		writePrimitive<uint16_t>(bvConstants::BV_UINT16, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint32 (uint32_t const v)
                                             {
		writePrimitive<uint32_t>(bvConstants::BV_UINT32, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint64 (uint64_t const v)
                                             {
		writePrimitive<uint64_t>(bvConstants::BV_UINT64, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Float (float const v)
                                         {
		writePrimitive<float>(bvConstants::BV_FLOAT, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Double (double const v)
                                           {
		writePrimitive<double>(bvConstants::BV_DOUBLE, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Bool (bool const v)
                                       {
		writePrimitive<uint8_t>(bvConstants::BV_BOOL, v ? 1 : 0);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (char const * str, uint32_t const len)
                                                                {
		onValueWritten();
		enc->parse<uint8_t>(bvConstants::BV_STRING);
		enc->parseString(str, len);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (char const * str)
                                            {
		return String(str, strlen(str));
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (STTSAV_STRING const & str)
                                                     {
		return String(str.data(), str.size());
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#define STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#define LZZ_OVERRIDE
// binaryValueWriter.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  int64_t BinaryValue::getInteger () const
                                   {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsNumber());

		switch (getBvType()) {
			case bvConstants::BV_INT8: {
				int8_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT16: {
				int16_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT32: {
				int32_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT64: {
				int64_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT8: {
				uint8_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT16: {
				uint16_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT32: {
				uint32_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT64: {
				uint64_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_FLOAT: {
				float v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_DOUBLE: {
				double v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			default:
				STTSAV_ASSERT(false);
				return 0;
			}
		}
}
namespace sttSav
{
  double BinaryValue::getFloating () const
                                   {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsNumber());

		switch (getBvType()) {
			case bvConstants::BV_INT8: {
				int8_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT16: {
				int16_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT32: {
				int32_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_INT64: {
				int64_t v;
				dec->parseAt(payloadOffset(), v);
				return (double)v;
				}
			case bvConstants::BV_UINT8: {
				uint8_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT16: {
				uint16_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT32: {
				uint32_t v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_UINT64: {
				uint64_t v;
				dec->parseAt(payloadOffset(), v);
				return (double)v;
				}
			case bvConstants::BV_FLOAT: {
				float v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			case bvConstants::BV_DOUBLE: {
				double v;
				dec->parseAt(payloadOffset(), v);
				return v;
				}
			default:
				STTSAV_ASSERT(false);
				return 0.0;
			}
		}
}
namespace sttSav
{
  STTSAV_STRING BinaryValue::GetString () const
                                        {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsString());
		STTSAV_STRING out;
		GetStringRef(out);
		return out;
		}
}
namespace sttSav
{
  void BinaryValue::GetStringRef (STTSAV_STRING & out) const
                                                    {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsString());
		StringDecoder d(*dec);
		d.seek = payloadOffset();
		d.parseString(out);
		}
}
namespace sttSav
{
  BinaryValue BinaryValue::operator [] (uint32_t index) const
                                                     {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsArray());
		STTSAV_ASSERT(index < Size());

		uint64_t off = childOffset();

		for (uint32_t i = 0; i < index; ++i) {
			BinaryValue v;
			v.dec = dec;
			v.offset = off;
			off = v.nextOffset();
			}

		BinaryValue out;
		out.dec = dec;
		out.offset = off;
		return out;
		}
}
namespace sttSav
{
  BinaryValue BinaryValue::operator [] (char const * key) const
                                                       {
		STTSAV_ASSERT(IsValid());
		STTSAV_ASSERT(IsObject());
		
		uint64_t off = childOffset();
		for (uint32_t i = 0; i < Size(); ++i) {
			StringDecoder d(*dec);
			d.seek = off;
			
			STTSAV_STRING name;
			d.parseString(name);

			if (name == key) {
				BinaryValue out;
				out.dec = dec;
				out.offset = d.seek;
				return out;
				}
			
			BinaryValue v;
			v.dec = dec;
			v.offset = d.seek;
			off = v.nextOffset();
			}
		return BinaryValue();
		}
}
namespace sttSav
{
  STTSAV_STRING BinaryValue::toDbgString () const
                                          {
		return toDbgStringIndented(0);
		}
}
namespace sttSav
{
  STTSAV_STRING BinaryValue::toDbgStringIndented (uint32_t indent) const
                                                                 {
		// Prints a human readable debug string
		constexpr uint32_t BUFFER_SIZE = 128;
		char buff[BUFFER_SIZE];
		STTSAV_STRING out;

		auto doIndent = [&](uint32_t n) {
			for (uint32_t i = 0; i < n; ++i)
				out += "    ";
			};

		if (!IsValid()) {
			out += "<invalid>";
			return out;
			}

		switch (getBvType()) {
			case bvConstants::BV_EMPTY:
				out += "(null)";
				break;
			case bvConstants::BV_BOOL:
				out += "(bool) ";
				out += GetBool() ? "true" : "false";
				break;
			case bvConstants::BV_INT8:
				snprintf(buff, BUFFER_SIZE, "(int8) %d", (int)GetInt8());
				out += buff;
				break;
			case bvConstants::BV_INT16:
				snprintf(buff, BUFFER_SIZE, "(int16) %d", (int)GetInt16());
				out += buff;
				break;
			case bvConstants::BV_INT32:
				snprintf(buff, BUFFER_SIZE, "(int32) %d", GetInt32());
				out += buff;
				break;
			case bvConstants::BV_INT64:
				snprintf(buff, BUFFER_SIZE, "(int64) %lld", (long long)GetInt64());
				out += buff;
				break;
			case bvConstants::BV_UINT8:
				snprintf(buff, BUFFER_SIZE, "(uint8) %u", (unsigned)GetUint8());
				out += buff;
				break;
			case bvConstants::BV_UINT16:
				snprintf(buff, BUFFER_SIZE, "(uint16) %u", (unsigned)GetUint16());
				out += buff;
				break;
			case bvConstants::BV_UINT32:
				snprintf(buff, BUFFER_SIZE, "(uint32) %u", GetUint32());
				out += buff;
				break;
			case bvConstants::BV_UINT64:
				snprintf(buff, BUFFER_SIZE, "(uint64) %llu", (unsigned long long)GetUint64());
				out += buff;
				break;
			case bvConstants::BV_FLOAT:
				snprintf(buff, BUFFER_SIZE, "(float) %g", GetFloat());
				out += buff;
				break;
			case bvConstants::BV_DOUBLE:
				snprintf(buff, BUFFER_SIZE, "(double) %g", GetDouble());
				out += buff;
				break;
			case bvConstants::BV_STRING:
				out += "(string) \"";
				out += GetString();
				out += "\"";
				break;
			case bvConstants::BV_ARRAY:
				out += "(array)\n";
				doIndent(indent);
				out += "[\n";
				for (uint32_t i = 0; i < Size(); ++i) {
					doIndent(indent + 1);
					out += (*this)[i].toDbgStringIndented(indent + 1);
					out += "\n";
					}
				doIndent(indent);
				out += "]";
				break;
			case bvConstants::BV_OBJECT: {
				out += "(object)\n";
				doIndent(indent);
				out += "{\n";
				uint64_t off = childOffset();
				for (uint32_t i = 0; i < Size(); ++i) {
					StringDecoder d(*dec);
					d.seek = off;
					
					STTSAV_STRING key;
					d.parseString(key);

					BinaryValue child;
					child.dec = dec;
					child.offset = d.seek;

					doIndent(indent + 1);
					out += key;
					out += ": ";
					out += child.toDbgStringIndented(indent + 1);
					out += "\n";

					off = child.nextOffset();
					}

				doIndent(indent);
				out += "}";
				break;
				}
			default:
				out += "<unknown>";
				break;
			}
		return out;
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// archiveFile.hh
//

#ifndef LZZ_archiveFile_hh
#define LZZ_archiveFile_hh
namespace sttSav {
struct archiveConstants {
	static constexpr uint32_t ARCHIVE_MAGIC = uint32_t('S') | (uint32_t('T') << 8) | (uint32_t('S') << 16) | (uint32_t('V') << 24);
	static constexpr uint16_t ARCHIVE_VERSION = 1;
	};
class ArchiveManager;
}
#define LZZ_INLINE inline
namespace sttSav
{
  struct ArchiveFileHeader
  {
    uint32_t magic;
    uint16_t version;
    uint16_t reserved;
    uint64_t directoryOffset;
    static uint64_t getDirectoryOffsetAddr (uint64_t const thisOffset);
  };
}
namespace sttSav
{
  struct ArchiveDirectoryHeader
  {
    uint32_t numRecords;
    uint32_t reserved;
    uint64_t nextDirectoryOffset;
    static uint64_t getDirectoryOffsetAddr (uint64_t const thisOffset);
  };
}
namespace sttSav
{
  class ArchiveFile
  {
  public:
    STTSAV_VECTOR <recordInfo> records;
    STTSAV_STRING filename;
    ArchiveFileHeader mHeader;
    archiveId aid;
    uint64_t fileLength;
    uint64_t wastedBytes;
    uint64_t lastDirectoryOffsetAddr;
    FileHandle file;
    bool hasLoadedRecords;
    bool fileExists;
    STTSAV_VECTOR <recordInfo> pendingRecords;
    STTSAV_STRING writeBuffer;
    ArchiveFile ();
    void initHeader ();
    void setFilename (ArchiveManager const & AM);
  protected:
    uint32_t findRecord (recordId const id) const;
    uint32_t findPendingRecord (recordId const id, bool const isForward = true) const;
    void appendPendingBlob (recordInfo & r, buffer const buff);
  public:
    bool loadRecord (recordId const id, STTSAV_STRING & recordOut);
    bool saveRecord (recordId const id, buffer const buff);
    bool deleteRecord (recordId const id);
    bool loadRecordsWorker ();
    void initNewFileWorker ();
    bool prepareFileForWriting ();
  protected:
    void applyDeltas (STTSAV_VECTOR <recordInfo> const & deltas);
  public:
    bool commit ();
    bool compact ();
  };
}
namespace sttSav
{
  LZZ_INLINE uint64_t ArchiveFileHeader::getDirectoryOffsetAddr (uint64_t const thisOffset)
                                                                                 {
		return thisOffset + sizeof(magic) + sizeof(version) + sizeof(reserved);
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t ArchiveDirectoryHeader::getDirectoryOffsetAddr (uint64_t const thisOffset)
                                                                                 {
		return thisOffset + sizeof(numRecords) + sizeof(reserved);
		}
}
namespace sttSav
{
  LZZ_INLINE ArchiveFile::ArchiveFile ()
    : aid ({0}), fileLength (0), wastedBytes (0), lastDirectoryOffsetAddr (0), hasLoadedRecords (false), fileExists (false)
                                                                                                                                           {
		initHeader();
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_archiveFile
#define STT_SAV_IMPL_DOUBLE_GUARD_archiveFile
#define LZZ_OVERRIDE
// archiveFile.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  void ArchiveFile::initHeader ()
                          {
		mHeader.magic = archiveConstants::ARCHIVE_MAGIC;
		mHeader.version = archiveConstants::ARCHIVE_VERSION;
		mHeader.reserved = 0;
		mHeader.directoryOffset = 0; // 0 => nullptr
		}
}
namespace sttSav
{
  void ArchiveFile::setFilename (ArchiveManager const & AM)
                                                   {
		char buff[1024];
		uint32_t len = 0;
		AM.mDictionary->getArchiveFilename(aid, buff, len, 1024);
		filename = AM.mBasePath + buff;
		}
}
namespace sttSav
{
  uint32_t ArchiveFile::findRecord (recordId const id) const
                                                     {
		// If this fails to compile be sure to #include <algorithm>
		auto it = std::lower_bound(records.begin(), records.end(), id, recordInfo::compareRecords());
		if (it == records.end() || it->record.value != id.value)
			return -1;
		return (it - records.begin());
		}
}
namespace sttSav
{
  uint32_t ArchiveFile::findPendingRecord (recordId const id, bool const isForward) const
                                                                                         {
		if (isForward) {
			for (uint32_t i = 0; i < pendingRecords.size(); ++i) {
				if (pendingRecords[i].record.value == id.value)
					return i;
				}
			}
		else {
			for (uint32_t i = pendingRecords.size()-1; i < pendingRecords.size(); --i) {
				if (pendingRecords[i].record.value == id.value)
					return i;
				}
			}
		return -1;
		}
}
namespace sttSav
{
  void ArchiveFile::appendPendingBlob (recordInfo & r, buffer const buff)
                                                                 {
		r.offset = writeBuffer.size();
		r.length = buff.len;
		writeBuffer.append((const char*) buff.data, buff.len);
		}
}
namespace sttSav
{
  bool ArchiveFile::loadRecord (recordId const id, STTSAV_STRING & recordOut)
                                                                     {
		STTSAV_ASSERT(hasLoadedRecords);
		recordOut.clear();

		// Check pending changes first (newest first).
		uint32_t p = findPendingRecord(id, false);
		if (p < pendingRecords.size()) {
			const recordInfo& r = pendingRecords[p];
			// Tombstone? => Record no longer exists
			if (r.length == 0)
				return true;
			STTSAV_ASSERT(r.offset + r.length <= writeBuffer.size());
			recordOut.assign(writeBuffer.data() + r.offset, r.length);
			return true;
			}

		// Check committed records.
		uint32_t idx = findRecord(id);
		if (idx >= records.size())
			return true;	// Record does not exist.

		const recordInfo& r = records[idx];
		
		// Lazily open the archive.
		if (!file.isOpen()) {
			if (!file.openRead(filename.c_str()))
				return false;
			}
		if (!file.seek(r.offset))
			return false;

		recordOut.resize(r.length);
		if (r.length) {
			if (!file.read(recordOut.data(), r.length))
				return false;
			}
		return true;
		}
}
namespace sttSav
{
  bool ArchiveFile::saveRecord (recordId const id, buffer const buff)
                                                              {
		STTSAV_ASSERT(hasLoadedRecords);

		// Remove any existing pending commits
		uint32_t p = findPendingRecord(id);
		if (p < pendingRecords.size())
			pendingRecords.erase(pendingRecords.begin() + p);

		recordInfo r;
		r.record = id;
		appendPendingBlob(r, buff);
		pendingRecords.push_back(r);
		return true;
		}
}
namespace sttSav
{
  bool ArchiveFile::deleteRecord (recordId const id)
                                             {
		STTSAV_ASSERT(hasLoadedRecords);

		// Remove any pending entry
		uint32_t p = findPendingRecord(id);
		while (p < pendingRecords.size()) {
			pendingRecords.erase(pendingRecords.begin() + p);
			p = findPendingRecord(id);
			}

		// Does it exist on disc?
		uint32_t idx = findRecord(id);
		if (idx >= records.size())
			return true; // not found, we don't need a tombstone

		recordInfo tombstone = records[idx];
		tombstone.length = 0;

		pendingRecords.push_back(tombstone);
		return true;
		}
}
namespace sttSav
{
  bool ArchiveFile::loadRecordsWorker ()
                                 {
		// Returns TRUE if archive is ok or truncated and we can recover feilds
		// Returns FALSE if archive is corrupt and unusable
		STTSAV_ASSERT(file.isOpen());
		fileLength = file.length();

		// Empty file?
		if (fileLength < sizeof(ArchiveFileHeader)) {
			hasLoadedRecords = true;
			lastDirectoryOffsetAddr = ArchiveFileHeader::getDirectoryOffsetAddr(0);
			return true;
			}

		// Read archive header.
		if (!file.seek(0))
			return false;

		if (!file.read(mHeader))
			return false;

		// Invalid archive.
		if (mHeader.magic != archiveConstants::ARCHIVE_MAGIC || mHeader.version != archiveConstants::ARCHIVE_VERSION)
			return false;

		// First directory has been truncated
		if (mHeader.directoryOffset > fileLength)
			return false;

		// No directories yet.
		if (mHeader.directoryOffset == 0) {
			hasLoadedRecords = true;
			lastDirectoryOffsetAddr = ArchiveFileHeader::getDirectoryOffsetAddr(0);
			return true;
			}

		uint64_t directoryOffset = mHeader.directoryOffset;

		while (directoryOffset) {
			// Truncated / corrupt tail.
			if (directoryOffset >= fileLength)
				break;
			if (!file.seek(directoryOffset))
				break;
			ArchiveDirectoryHeader dh;
			if (!file.read(dh))
				break;
			// Validate that the entire delta fits in the file.
			const uint64_t deltaEnd = directoryOffset + sizeof(ArchiveDirectoryHeader) + uint64_t(dh.numRecords) * sizeof(recordInfo);

			if (deltaEnd > fileLength)
				break;

			STTSAV_VECTOR<recordInfo> delta;
			delta.resize(dh.numRecords);

			if (!file.readArray(delta.data(), dh.numRecords))
				break;

			// Apply this delta.
			applyDeltas(delta);

			// Remember where the next directory pointer lives.
			lastDirectoryOffsetAddr = ArchiveDirectoryHeader::getDirectoryOffsetAddr(directoryOffset);

			// Self-loop protection.
			if (dh.nextDirectoryOffset == directoryOffset)
				break;

			directoryOffset = dh.nextDirectoryOffset;
			}

		hasLoadedRecords = true;
		fileLength = file.length();
		return true;
		}
}
namespace sttSav
{
  void ArchiveFile::initNewFileWorker ()
                                 {
		STTSAV_ASSERT(file.isOpen());
		
		initHeader();
		lastDirectoryOffsetAddr = mHeader.getDirectoryOffsetAddr(0);
		hasLoadedRecords = true;
		
		if (!file.write(mHeader))
			STTSAV_ASSERT(false);

		fileLength = sizeof(ArchiveFileHeader);
		}
}
namespace sttSav
{
  bool ArchiveFile::prepareFileForWriting ()
                                     {
		// Already open for read/write?
		if (file.isOpen() && file.getMode() == FileHandle::OM_READ_WRITE)
			return true;

		// Upgrade a read-only handle.
		if (file.isOpen())
			file.close();

		if (!fileExists) {
			// First write to this archive.
			if (!file.openReadWrite(filename.c_str(), true))
				return false;

			initNewFileWorker();
			}
		else {
			// Existing archive.
			if (!file.openReadWrite(filename.c_str(), false))
				return false;
				
			if (!hasLoadedRecords) {
				bool isOk = loadRecordsWorker();
				
				if (!isOk) {
					// corrupted. create a new blank file
					if (!file.truncateAndReopen(filename.c_str()))
						return false;
					initNewFileWorker();
					}
				}
			}

		return true;
		}
}
namespace sttSav
{
  void ArchiveFile::applyDeltas (STTSAV_VECTOR <recordInfo> const & deltas)
                                                                  {
		for (const recordInfo& r : deltas) {
			uint32_t idx = findRecord(r.record);
			if (r.length == 0) {
				// Delete existing record.
				if (idx < records.size())
					records.erase(records.begin() + idx);
				continue;
				}
			if (idx < records.size()) {
				// Replace existing record.
				records[idx] = r;
				}
			else {
				// Insert new record, maintaining sorted order.
				auto it = std::lower_bound( records.begin(), records.end(), r.record, recordInfo::compareRecords());
				records.insert(it, r);
				}
			}
		}
}
namespace sttSav
{
  bool ArchiveFile::commit ()
                      {
		if (pendingRecords.empty())
			return true;

		// Phase 1 - get a valid write file handle
		if (!prepareFileForWriting()) {
			// error! we have no valid file handle
			return false;
			}
		STTSAV_ASSERT(hasLoadedRecords);

		// Phase 2 - write pending blob data to disc
		{
		file.seek(fileLength);
		for (recordInfo& r : pendingRecords) {
			if (r.length == 0)
				continue;
			const char* src = writeBuffer.data() + r.offset;
			if (!file.write(src, r.length))
				return false;
			r.offset = fileLength;
			fileLength += r.length;
			}
		}
		
		// Phase 3 - Write directory updates.
		const uint64_t newDirectoryOffset = fileLength;
		{
			ArchiveDirectoryHeader dh;
			dh.numRecords = pendingRecords.size();
			dh.reserved = 0;
			dh.nextDirectoryOffset = 0;

			if (!file.write(dh))
				return false;
			
			// Just memcpy the vector to file
			STTSAV_ASSERT(std::is_trivially_copyable<recordInfo>::value);
			if (!pendingRecords.empty())
				if (!file.writeArray( pendingRecords.data(), pendingRecords.size() ))
					return false;
				
			fileLength += sizeof(ArchiveDirectoryHeader) + (pendingRecords.size() * sizeof(recordInfo));
		}

		// Phase 4 - Link the new directory into the directory chain.
		{
			// Update the previous directory (or header for the first directory) to
			// point at this newly written directory.
			if (!file.seek(lastDirectoryOffsetAddr))
				return false;

			if (!file.write(newDirectoryOffset))
				return false;

			// Remember where this directory's "next directory" pointer lives.
			lastDirectoryOffsetAddr = ArchiveDirectoryHeader::getDirectoryOffsetAddr(newDirectoryOffset);
		}

		// Phase 5 - Apply pending changes to the in-memory directory.
		applyDeltas(pendingRecords);

		pendingRecords.clear();
		pendingRecords.shrink_to_fit();
		writeBuffer.clear();
		writeBuffer.shrink_to_fit();

		return true;
		}
}
namespace sttSav
{
  bool ArchiveFile::compact ()
                       {
		// Cleans the archive file, removing dead blobs and cleaning up the record directory
		
		// Nothing to compact.
		if (!fileExists)
			return true;
			
		// Ensure the archive is realised.
		if (!hasLoadedRecords) {
			if (!prepareFileForWriting())
				return false;
			}

		// Commit any pending writes first.
		if (!pendingRecords.empty()) {
			if (!commit())
				return false;
			}
			
		// Delete if no records
		if (!records.size()) {
			if (file.isOpen())
				file.close();
			FileOps::deleteFile(filename.c_str());
			fileExists = false;
			fileLength = 0;
			wastedBytes = 0;
			return true;
			}

		// Open source archive if necessary.
		if (!file.isOpen()) {
			if (!file.openRead(filename.c_str()))
				return false;
			}

		// Phase 1 - Create temporary archive.
		STTSAV_STRING tmpFilename = filename + ".tmp";

		FileHandle out;
		if (!out.openReadWrite(tmpFilename.c_str(), true))
			return false;
		
		// Guard to remove temp in case of failure
		struct tempFileGuard {
			FileHandle* tmpOut;
			const char* tmpName;
			
			~tempFileGuard() {
				if (tmpOut) {
					tmpOut->close();
					FileOps::deleteFile(tmpName);
					}
				}
			};
		tempFileGuard G;
		G.tmpOut = &out;
		G.tmpName = tmpFilename.c_str();

		// Start writing output
		ArchiveFileHeader newHeader;
		newHeader.magic = archiveConstants::ARCHIVE_MAGIC;
		newHeader.version = archiveConstants::ARCHIVE_VERSION;
		newHeader.reserved = 0;
		newHeader.directoryOffset = sizeof(ArchiveFileHeader);

		if (!out.write(newHeader))
			return false;

		uint64_t nextOffset = sizeof(ArchiveFileHeader);

		// Phase 2 - Copy all live blobs.
		STTSAV_STRING blobBuffer;

		for (recordInfo& r : records) {
			if (!FileHandle::copyRange(file, r.offset, r.length, out))
				return false;

			r.offset = nextOffset;
			nextOffset += r.length;
			}

		// Phase 3 - Write a single directory.
		const uint64_t directoryOffset = nextOffset;

		ArchiveDirectoryHeader dh;
		dh.numRecords = (uint32_t)records.size();
		dh.reserved = 0;
		dh.nextDirectoryOffset = 0;

		if (!out.write(dh))
			return false;

		if (!out.writeArray(records.data(), (uint32_t)records.size()))
			return false;
			
		nextOffset += sizeof(ArchiveDirectoryHeader) + (uint64_t(records.size()) * sizeof(recordInfo));

		// Phase 4 - Patch the header.
		newHeader.directoryOffset = directoryOffset;

		if (!out.seek(0))
			return false;

		if (!out.write(newHeader))
			return false;

		if (!out.flush())
			return false;

		out.close();
		G.tmpOut = NULL; // disarm the guard

		// Phase 5 - Replace the old archive.
		file.close();

		if (!FileOps::replace(tmpFilename.c_str(), filename.c_str()))
			return false;

		// Re-open lazily later.
		fileLength = nextOffset;
		wastedBytes = 0;
		lastDirectoryOffsetAddr = ArchiveDirectoryHeader::getDirectoryOffsetAddr(directoryOffset);
		return true;
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_archiveFile
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// archiveManager.hh
//

#ifndef LZZ_archiveManager_hh
#define LZZ_archiveManager_hh
#define LZZ_INLINE inline
namespace sttSav
{
  class ArchiveManager
  {
  public:
    ArchiveDictionaryI * mDictionary;
    STTSAV_STRING mBasePath;
    float compactionRatio;
    uint32_t maxArchiveSize;
    uint32_t minimumArchiveSize;
  protected:
    bool keepFilesOpen;
  public:
    STTSAV_VECTOR <ArchiveFile*> mArchives;
    ArchiveManager (ArchiveDictionaryI * _mDictionary);
    ~ ArchiveManager ();
    bool loadRecord (archiveKey const key, recordId const record, STTSAV_STRING & out);
    bool saveRecord (archiveKey const key, recordId const record, char const * buff, uint32_t const len);
    bool saveRecord (archiveKey const key, recordId const record, buffer const buff);
    bool deleteRecord (archiveKey const key, recordId const record);
    bool compactArchive (archiveKey const key, bool const forceCompact);
    bool splitArchive (archiveKey const key, bool const forceSplit);
    bool joinArchive (archiveKey const key, bool const forceJoin);
    void startBulkTransations ();
    void doTransactions (transaction * mTransactions, int const nTransactions);
    void closeOpenFiles ();
    void endBulkTransations ();
    void extractRecordsList (archiveId const id, STTSAV_VECTOR <recordInfo> & out);
    bool writeDictionary ();
    bool readDictionary ();
  };
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_archiveManager
#define STT_SAV_IMPL_DOUBLE_GUARD_archiveManager
#define LZZ_OVERRIDE
// archiveManager.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  ArchiveManager::ArchiveManager (ArchiveDictionaryI * _mDictionary)
                                                         {
		mDictionary = _mDictionary;
		compactionRatio = 1.5;
		maxArchiveSize = 8388608; // 8MB
		minimumArchiveSize = 1048576; // 1MB
		keepFilesOpen = false;
		}
}
namespace sttSav
{
  ArchiveManager::~ ArchiveManager ()
                          {
		closeOpenFiles();
		}
}
namespace sttSav
{
  bool ArchiveManager::loadRecord (archiveKey const key, recordId const record, STTSAV_STRING & out)
                                                                                         {
		transaction t = transaction::makeLoad(key, record, out);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::saveRecord (archiveKey const key, recordId const record, char const * buff, uint32_t const len)
                                                                                                           {
		return saveRecord(key, record, buffer(buff, len));
		}
}
namespace sttSav
{
  bool ArchiveManager::saveRecord (archiveKey const key, recordId const record, buffer const buff)
                                                                                        {
		transaction t = transaction::makeSave(key, record, buff);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::deleteRecord (archiveKey const key, recordId const record)
                                                                       {
		transaction t = transaction::makeDelete(key, record);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::compactArchive (archiveKey const key, bool const forceCompact)
                                                                           {
		transaction t = transaction::makeCompact(key, forceCompact);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::splitArchive (archiveKey const key, bool const forceSplit)
                                                                       {
		transaction t = transaction::makeCompact(key, forceSplit);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::joinArchive (archiveKey const key, bool const forceJoin)
                                                                     {
		transaction t = transaction::makeCompact(key, forceJoin);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  void ArchiveManager::startBulkTransations ()
                                    {
		keepFilesOpen = true;
		}
}
namespace sttSav
{
  void ArchiveManager::doTransactions (transaction * mTransactions, int const nTransactions)
                                                                                 {
		// transactionMode = normal, flush. 
		//  - normal: writes to disc, and does splitting and compacting where appropriate
		//	- flush: writes to disc but doesn't do splitting, compacting. Use on app save & exit
		
		// Bulk load/save/delete to save file ops
		// first resolve mKey -> archiveId
		//...
		// determine if we need to split files, etc
		//...
		// perform transactions in non-conflicting order
		//...
		
		if (!keepFilesOpen)
			closeOpenFiles();
		}
}
namespace sttSav
{
  void ArchiveManager::closeOpenFiles ()
                              {
		//...
		}
}
namespace sttSav
{
  void ArchiveManager::endBulkTransations ()
                                  {
		// close any open files here
		closeOpenFiles();
		keepFilesOpen = false;
		}
}
namespace sttSav
{
  void ArchiveManager::extractRecordsList (archiveId const id, STTSAV_VECTOR <recordInfo> & out)
                                                                                    {}
}
namespace sttSav
{
  bool ArchiveManager::writeDictionary ()
                               { return false; }
}
namespace sttSav
{
  bool ArchiveManager::readDictionary ()
                              { return false; }
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_archiveManager
#endif //STT_SAV_IMPL_IMPL
