// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// sttSav.hh
//

#ifndef LZZ_sttSav_hh
#define LZZ_sttSav_hh
// Header file
#ifndef STTSAV_STRING
	#define STTSAV_STRING std::string
#endif
#ifndef STTSAV_VECTOR
	#define STTSAV_VECTOR std::vector
#endif
namespace sttSav {
struct archiveId { uint32_t value; };
struct recordId  { uint32_t value; };
struct archiveKey { uint32_t value; };

struct recordInfo {
	archiveKey key;
	recordId record;
	uint32_t offset;
	uint32_t length;
	};
struct splitResult {
    archiveId aid;
    uint32_t size;
	};

class ArchiveDictionaryI {
public:
	/// Archive dictionary interface
	///
	/// An ArchiveDictionaryI maps application-defined archive keys to archive IDs.
	/// The dictionary is responsible for generating archive keys and determining
	/// which archive owns a particular key. It contains no file I/O logic and is
	/// independent of the archive storage format.
	///
	/// Different applications may implement different dictionary strategies
	/// (planetary quadtree, fixed grid, hash table, etc.) while sharing the same
	/// archive storage engine.
	
	inline ArchiveDictionaryI() {}
	virtual ~ArchiveDictionaryI() {}
	
	//archiveKey buildKey(...) // <-- you should have some kind of buildKey function per dictionary
	virtual archiveId getArchiveId(const archiveKey key) const = 0;
	
	// Fast lookup of archives from a shortlist produced with splitArchive. Falls back to getArchiveId
	virtual archiveId getArchiveIdFromShortlist(const archiveKey key, const splitResult* resultsIn, const uint32_t numResults) const { return getArchiveId(key); }
	
	// Returns a name of an archive
	virtual void getArchiveFilename(const archiveId id, char* nameOut, uint32_t& lenOut, const uint32_t maxLen) const {
		lenOut = snprintf(nameOut, maxLen, "archive%i.sav", (int) id.value);
		}
	
	// Splits an archive into 
	// RETURNS
	// - a list of children archives that should hold all of the records within archiveId id. This may or may not contain archiveId
	// - numChildrenOut - the number of children returned
	// - splitInfoOut - the kind of split that was perfomed. You can use getArchiveIdFromShortlist with this value to accelerte lookup of archives from keys 
	// bool - if a split happened or not
	virtual bool splitArchive(const archiveId id, const STTSAV_VECTOR<recordInfo>& records, const uint32_t maxArchiveSize, splitResult* resultsOut, uint32_t& numResultsOut, const uint32_t maxChildrenOut) = 0;
	
	// For a given archive determine what other archives can be combined according to this dictionary's topology
	// Returns false if there is no legal merge possible
	virtual bool getMergeCandidates(const archiveId id, archiveId* archivesOut, uint32_t& numArchivesOut, const uint32_t maxArchivesOut) const = 0;
	
	// Commits the merge in the dictionary, from the list provided by getMergeCandidates
	virtual bool mergeArchives(const archiveId* archives, const uint32_t numArchives) = 0;
	
	};
	
struct transactionMode {
	constexpr static uint8_t TM_UNKOWN = 0;
	constexpr static uint8_t TM_LOAD = 1;
	constexpr static uint8_t TM_SAVE = 2;
	constexpr static uint8_t TM_DELETE  = 3;
	constexpr static uint8_t TM_COMPACT = 4;
	constexpr static uint8_t TM_SPLIT = 5;
	constexpr static uint8_t TM_JOIN  = 6;
	constexpr static uint8_t TM_count  = 7;
	};
} // namespace sttSav
#define LZZ_INLINE inline
namespace sttSav
{
  struct buffer
  {
    uint8_t const * data;
    uint32_t len;
    buffer ();
    buffer (char const * _buff, uint32_t const _len);
  };
}
namespace sttSav
{
  struct transaction
  {
    archiveKey mKey;
    recordId mRecord;
    uint8_t mode;
    buffer mBufferOut;
    STTSAV_STRING * stringOut;
    bool forceOperation;
    bool success;
    void initToZero ();
    static transaction makeLoad (archiveKey const _mKey, recordId const _mRecord, STTSAV_STRING & out);
    static transaction makeSave (archiveKey const _mKey, recordId const _mRecord, char const * buff, uint32_t const len);
    static transaction makeSave (archiveKey const _mKey, recordId const _mRecord, buffer const _buff);
    static transaction makeDelete (archiveKey const _mKey, recordId const _mRecord);
    static transaction makeCompact (archiveKey const _mKey, bool const forceCompact);
    static transaction makeSplit (archiveKey const _mKey, bool const forceSplit);
    static transaction makeJoin (archiveKey const _mKey, bool const forceJoin);
  };
}
namespace sttSav
{
  struct recordHeaderShort
  {
    recordId id;
    uint32_t offset;
  };
}
namespace sttSav
{
  class ArchiveManager
  {
  public:
    ArchiveDictionaryI * mDictionary;
    STTSAV_STRING mBasePath;
    float compactionRatio;
    uint32_t maxArchiveSize;
    uint32_t minimumArchiveSize;
  protected:
    bool keepFilesOpen;
  public:
    ArchiveManager (ArchiveDictionaryI * _mDictionary);
    ~ ArchiveManager ();
    bool loadRecord (archiveKey const key, recordId const record, STTSAV_STRING & out);
    bool saveRecord (archiveKey const key, recordId const record, char const * buff, uint32_t const len);
    bool saveRecord (archiveKey const key, recordId const record, buffer const buff);
    bool deleteRecord (archiveKey const key, recordId const record);
    bool compactArchive (archiveKey const key, bool const forceCompact);
    bool splitArchive (archiveKey const key, bool const forceSplit);
    bool joinArchive (archiveKey const key, bool const forceJoin);
    void startBulkTransations ();
    void doTransactions (transaction * mTransactions, int const nTransactions);
    void closeOpenFiles ();
    void endBulkTransations ();
    void extractRecordsList (archiveId const id, STTSAV_VECTOR <recordInfo> & out);
    bool writeDictionary ();
    bool readDictionary ();
  };
}
namespace sttSav
{
  LZZ_INLINE buffer::buffer ()
                        {}
}
namespace sttSav
{
  LZZ_INLINE buffer::buffer (char const * _buff, uint32_t const _len)
    : data ((const uint8_t*)_buff), len (_len)
                                                                                                       {}
}
namespace sttSav
{
  LZZ_INLINE void transaction::initToZero ()
                                 {
		mKey.value = 0;
		mRecord.value = 0;
		mode = transactionMode::TM_UNKOWN;
		mBufferOut.data = 0;
		mBufferOut.len = 0;
		stringOut = NULL;
		forceOperation = false;
		success = false;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeLoad (archiveKey const _mKey, recordId const _mRecord, STTSAV_STRING & out)
                                                                                                                {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mRecord = _mRecord;
		r.mode = transactionMode::TM_LOAD;
		r.stringOut = &out;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeSave (archiveKey const _mKey, recordId const _mRecord, char const * buff, uint32_t const len)
                                                                                                                                  {
		return makeSave(_mKey, _mRecord, buffer(buff, len));
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeSave (archiveKey const _mKey, recordId const _mRecord, buffer const _buff)
                                                                                                                {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mRecord = _mRecord;
		r.mode = transactionMode::TM_SAVE;
		r.mBufferOut = _buff;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeDelete (archiveKey const _mKey, recordId const _mRecord)
                                                                                              {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mRecord = _mRecord;
		r.mode = transactionMode::TM_DELETE;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeCompact (archiveKey const _mKey, bool const forceCompact)
                                                                                               {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mode = transactionMode::TM_COMPACT;
		r.forceOperation = forceCompact;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeSplit (archiveKey const _mKey, bool const forceSplit)
                                                                                           {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mode = transactionMode::TM_SPLIT;
		r.forceOperation = forceSplit;
		return r;
		}
}
namespace sttSav
{
  LZZ_INLINE transaction transaction::makeJoin (archiveKey const _mKey, bool const forceJoin)
                                                                                         {
		transaction r; r.initToZero();
		r.mKey = _mKey;
		r.mode = transactionMode::TM_JOIN;
		r.forceOperation = forceJoin;
		return r;
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_sttSav
#define STT_SAV_IMPL_DOUBLE_GUARD_sttSav
#define LZZ_OVERRIDE
// sttSav.cpp
//

// Implmentation file
#define LZZ_INLINE inline
namespace sttSav
{
  ArchiveManager::ArchiveManager (ArchiveDictionaryI * _mDictionary)
                                                         {
		mDictionary = _mDictionary;
		compactionRatio = 1.5;
		maxArchiveSize = 8388608; // 8MB
		minimumArchiveSize = 1048576; // 1MB
		keepFilesOpen = false;
		}
}
namespace sttSav
{
  ArchiveManager::~ ArchiveManager ()
                          {
		closeOpenFiles();
		}
}
namespace sttSav
{
  bool ArchiveManager::loadRecord (archiveKey const key, recordId const record, STTSAV_STRING & out)
                                                                                         {
		transaction t = transaction::makeLoad(key, record, out);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::saveRecord (archiveKey const key, recordId const record, char const * buff, uint32_t const len)
                                                                                                           {
		return saveRecord(key, record, buffer(buff, len));
		}
}
namespace sttSav
{
  bool ArchiveManager::saveRecord (archiveKey const key, recordId const record, buffer const buff)
                                                                                        {
		transaction t = transaction::makeSave(key, record, buff);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::deleteRecord (archiveKey const key, recordId const record)
                                                                       {
		transaction t = transaction::makeDelete(key, record);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::compactArchive (archiveKey const key, bool const forceCompact)
                                                                           {
		transaction t = transaction::makeCompact(key, forceCompact);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::splitArchive (archiveKey const key, bool const forceSplit)
                                                                       {
		transaction t = transaction::makeCompact(key, forceSplit);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  bool ArchiveManager::joinArchive (archiveKey const key, bool const forceJoin)
                                                                     {
		transaction t = transaction::makeCompact(key, forceJoin);
		doTransactions(&t, 1);
		return t.success;
		}
}
namespace sttSav
{
  void ArchiveManager::startBulkTransations ()
                                    {
		keepFilesOpen = true;
		}
}
namespace sttSav
{
  void ArchiveManager::doTransactions (transaction * mTransactions, int const nTransactions)
                                                                                 {
		// transactionMode = normal, flush. 
		//  - normal: writes to disc, and does splitting and compacting where appropriate
		//	- flush: writes to disc but doesn't do splitting, compacting. Use on app save & exit
		
		// Bulk load/save/delete to save file ops
		// first resolve mKey -> archiveId
		//...
		// determine if we need to split files, etc
		//...
		// perform transactions in non-conflicting order
		//...
		
		if (!keepFilesOpen)
			closeOpenFiles();
		}
}
namespace sttSav
{
  void ArchiveManager::closeOpenFiles ()
                              {
		//...
		}
}
namespace sttSav
{
  void ArchiveManager::endBulkTransations ()
                                  {
		// close any open files here
		closeOpenFiles();
		keepFilesOpen = false;
		}
}
namespace sttSav
{
  void ArchiveManager::extractRecordsList (archiveId const id, STTSAV_VECTOR <recordInfo> & out)
                                                                                    {}
}
namespace sttSav
{
  bool ArchiveManager::writeDictionary ()
                               { return false; }
}
namespace sttSav
{
  bool ArchiveManager::readDictionary ()
                              { return false; }
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_sttSav
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// splitBucket.hh
//

#ifndef LZZ_splitBucket_hh
#define LZZ_splitBucket_hh
#define LZZ_INLINE inline
namespace sttSav
{
  struct splitBucket
  {
    uint32_t value;
    uint32_t bytes;
    splitBucket ();
    splitBucket (uint32_t const _value, uint32_t const _bytes);
    bool operator < (splitBucket const & other) const;
    static void appendOrInsert (STTSAV_VECTOR <splitBucket> & buckets, uint32_t const _value, uint32_t const _bytes);
  };
}
namespace sttSav
{
  LZZ_INLINE splitBucket::splitBucket ()
                             { value = 0; bytes = 0; }
}
namespace sttSav
{
  LZZ_INLINE splitBucket::splitBucket (uint32_t const _value, uint32_t const _bytes)
                                                                         { value = _value; bytes = _bytes; }
}
namespace sttSav
{
  LZZ_INLINE bool splitBucket::operator < (splitBucket const & other) const
                                                                 { return bytes < other.bytes; }
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_splitBucket
#define STT_SAV_IMPL_DOUBLE_GUARD_splitBucket
#define LZZ_OVERRIDE
// splitBucket.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  void splitBucket::appendOrInsert (STTSAV_VECTOR <splitBucket> & buckets, uint32_t const _value, uint32_t const _bytes)
                                                                                                                      {
		for (splitBucket& b : buckets) {
			if (b.value == _value) {
				b.bytes += _bytes;
				return;
				}
			}
		buckets.push_back(splitBucket(_value, _bytes));
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_splitBucket
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// stringEncoder.hh
//

#ifndef LZZ_stringEncoder_hh
#define LZZ_stringEncoder_hh
#define LZZ_INLINE inline
namespace sttSav
{
  class StringEncoder
  {
  public:
    STTSAV_STRING & buff;
    StringEncoder (STTSAV_STRING & storage);
    void reserve (uint32_t const initialCapacity);
    uint64_t getSeek () const;
    template <typename T>
    void parse (T const & t);
    template <typename T>
    void parseAt (uint64_t const offset, T const & value);
    void parseSize (uint64_t const trueSize);
    void parseString (STTSAV_STRING const & str);
    void parseString (char const * str, uint32_t const sz);
  };
}
namespace sttSav
{
  class StringDecoder
  {
  public:
    STTSAV_STRING const & buff;
    uint64_t seek;
    bool hasError;
    StringDecoder (STTSAV_STRING const & _src);
    bool isOk () const;
    void onBufferOverflow (uint64_t const read);
    bool checkError2 (uint64_t const read);
    template <typename T>
    void parse (T & tout);
    template <typename T>
    T parse ();
    template <typename T>
    void parseAt (uint64_t offset, T & tout) const;
    void parseString (STTSAV_STRING & out);
    uint64_t parseSize ();
  };
}
namespace sttSav
{
  LZZ_INLINE StringEncoder::StringEncoder (STTSAV_STRING & storage)
    : buff (storage)
                                                                     {}
}
namespace sttSav
{
  LZZ_INLINE void StringEncoder::reserve (uint32_t const initialCapacity)
                                                            {
		buff.reserve(initialCapacity);
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t StringEncoder::getSeek () const
                                        { return buff.size(); }
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringEncoder::parse (T const & t)
                                       {
		buff += std::string_view((char*)&t, sizeof(T));
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringEncoder::parseAt (uint64_t const offset, T const & value)
                                                                   {
		memcpy(&buff[offset], &value, sizeof(T));
		}
}
namespace sttSav
{
  LZZ_INLINE void StringEncoder::parseSize (uint64_t const trueSize)
                                                       {
		if (trueSize >= uint8_t(-1)) {
			parse<uint8_t>(-1);
			parse<uint64_t>(trueSize);
			}
		else
			parse<uint8_t>(trueSize);
		}
}
namespace sttSav
{
  LZZ_INLINE StringDecoder::StringDecoder (STTSAV_STRING const & _src)
    : buff (_src), seek (0), hasError (false)
                                                                                                {}
}
namespace sttSav
{
  LZZ_INLINE bool StringDecoder::isOk () const
                                 { return !hasError; }
}
namespace sttSav
{
  LZZ_INLINE bool StringDecoder::checkError2 (uint64_t const read)
                                                     {
		if (hasError) return true;
		if (read + seek > buff.size()) {
			onBufferOverflow(read);
			hasError = true;
			}
		return hasError;
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringDecoder::parse (T & tout)
                                    {
		if (checkError2(sizeof(T))) return;
		buff.copy((char *) &tout, sizeof(T), seek);
		seek += sizeof(T);
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE T StringDecoder::parse ()
                         {
		if (checkError2(sizeof(T))) return T();
		T tout;
		buff.copy((char *) &tout, sizeof(T), seek);
		seek += sizeof(T);
		return tout;
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void StringDecoder::parseAt (uint64_t offset, T & tout) const
                                                            {
		buff.copy((char *) &tout, sizeof(T), offset);
		}
}
namespace sttSav
{
  LZZ_INLINE void StringDecoder::parseString (STTSAV_STRING & out)
                                                    {
		uint64_t sz = parseSize();
		seek += sz;
		out = buff.substr(seek-sz, sz);
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t StringDecoder::parseSize ()
                                    {
		uint64_t sz = parse<uint8_t>();
		if (sz == uint8_t(-1))
			sz = parse<uint64_t>();
		return sz;
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#define STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#define LZZ_OVERRIDE
// stringEncoder.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  void StringEncoder::parseString (STTSAV_STRING const & str)
                                                    {
		parseSize(str.size());
		buff += str;
		}
}
namespace sttSav
{
  void StringEncoder::parseString (char const * str, uint32_t const sz)
                                                             {
		parseSize(sz);
		buff += str;
		}
}
namespace sttSav
{
  void StringDecoder::onBufferOverflow (uint64_t const read)
                                                   {
		printf("stt-sav buffer overflow! read %i at %i of string size %i\n", (int)read, (int)seek, (int)buff.size());
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_stringEncoder
#endif //STT_SAV_IMPL_IMPL
// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// binaryValueWriter.hh
//

#ifndef LZZ_binaryValueWriter_hh
#define LZZ_binaryValueWriter_hh
namespace sttSav {
struct bvConstants {
	static constexpr uint8_t BV_EMPTY = 0;
	static constexpr uint8_t BV_BOOL = 1;
static constexpr uint8_t BV_NUMBERS_START = 2;
	static constexpr uint8_t BV_FLOAT = 2;
	static constexpr uint8_t BV_DOUBLE = 3;
	static constexpr uint8_t BV_UINT8 = 4;
	static constexpr uint8_t BV_UINT16 = 5;
	static constexpr uint8_t BV_UINT32 = 6;
	static constexpr uint8_t BV_UINT64 = 7;
	static constexpr uint8_t BV_INT8 = 8;
	static constexpr uint8_t BV_INT16 = 9;
	static constexpr uint8_t BV_INT32 = 10;
	static constexpr uint8_t BV_INT64 = 11;
static constexpr uint8_t BV_NUMBERS_END = 11;
	static constexpr uint8_t BV_STRING = 12;
	static constexpr uint8_t BV_OBJECT = 13;
	static constexpr uint8_t BV_ARRAY = 14;
	};
}
#define LZZ_INLINE inline
namespace sttSav
{
  class BinaryValue
  {
  public:
    StringDecoder * dec;
    uint64_t offset;
  public:
    BinaryValue ();
  protected:
    uint8_t getBvType () const;
    uint64_t payloadOffset () const;
    uint32_t getJumpSize () const;
    uint32_t getMemberCount () const;
    uint64_t childOffset () const;
    uint64_t nextOffset () const;
  public:
    bool IsArray () const;
    bool IsObject () const;
    bool IsString () const;
    bool IsBool () const;
    bool IsNumber () const;
    uint32_t Size () const;
    int GetInt () const;
    uint32_t GetUint () const;
    int32_t GetInt32 () const;
    uint32_t GetUint32 () const;
    int64_t GetInt64 () const;
    uint64_t GetUint64 () const;
    float GetFloat () const;
    double GetDouble () const;
    bool GetBool () const;
    STTSAV_STRING GetString () const;
    void GetStringRef (STTSAV_STRING & out) const;
    uint32_t GetStringLength () const;
    BinaryValue operator [] (uint32_t index);
    BinaryValue operator [] (char const * key);
  };
}
namespace sttSav
{
  class BinaryWriter
  {
  public:
    StringEncoder * enc;
  protected:
    struct scope
    {
      uint64_t startOffset;
      uint32_t memberCount;
      bool isObject;
    };
    STT_SAV_VECTOR <scope> stack;
  public:
    BinaryWriter ();
  protected:
    void onValueWritten ();
    void startContainer (uint8_t const bvType, bool const isObject);
    void endContainer ();
    template <typename T>
    void writePrimitive (uint8_t const bvType, T const value);
  public:
    void StartObject ();
    void StartArray ();
    void EndObject ();
    void EndArray ();
    void Key (char const * str);
    void Int (int const v);
    void Int8 (int8_t const v);
    void Int16 (int16_t const v);
    void Int32 (int32_t const v);
    void Int64 (int64_t const v);
    void Uint (unsigned int const v);
    void Uint8 (uint8_t const v);
    void Uint16 (uint16_t const v);
    void Uint32 (uint32_t const v);
    void Uint64 (uint64_t const v);
    void Float (float const v);
    void Double (double const v);
    void Bool (bool const v);
    void String (char const * str, uint32_t const len);
    void String (char const * str);
    void String (STTSAV_STRING const & str);
  };
}
namespace sttSav
{
  LZZ_INLINE BinaryValue::BinaryValue ()
    : dec (NULL), offset (0)
                                                {}
}
namespace sttSav
{
  LZZ_INLINE uint8_t BinaryValue::getBvType () const
                                         {
		return dec->buff[offset];
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::payloadOffset () const
                                              {
		return offset + 1;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::getJumpSize () const
                                            {
		uint32_t v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::getMemberCount () const
                                               {
		uint32_t v;
		dec->parseAt(payloadOffset() + sizeof(uint32_t), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::childOffset () const
                                            {
		return payloadOffset() + sizeof(uint32_t) * 2;
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::nextOffset () const
                                           {
		switch (getBvType()) {
			case bvConstants::BV_BOOL:
			case bvConstants::BV_UINT8:
			case bvConstants::BV_INT8:
				return offset + 2;

			case bvConstants::BV_UINT16:
			case bvConstants::BV_INT16:
				return offset + 3;

			case bvConstants::BV_FLOAT:
			case bvConstants::BV_UINT32:
			case bvConstants::BV_INT32:
				return offset + 5;

			case bvConstants::BV_DOUBLE:
			case bvConstants::BV_UINT64:
			case bvConstants::BV_INT64:
				return offset + 9;

			case bvConstants::BV_STRING: {
				StringDecoder d(*dec);
				d.seek = payloadOffset();
				uint64_t sz = d.parseSize();
				return d.seek + sz;
				}

			case bvConstants::BV_ARRAY:
			case bvConstants::BV_OBJECT:
				return offset + getJumpSize();

			default:
				STTSAV_ASSERT(false);
				return offset;
			}
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsArray () const
                                    {
		return getBvType() == bvConstants::BV_ARRAY;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsObject () const
                                     {
		return getBvType() == bvConstants::BV_OBJECT;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsString () const
                                     {
		return getBvType() == bvConstants::BV_STRING;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsBool () const
                                   {
		return getBvType() == bvConstants::BV_BOOL;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::IsNumber () const
                                     {
		const uint8_t t = getBvType();
		return t >= bvConstants::BV_NUMBERS_START && t <= bvConstants::BV_NUMBERS_END;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::Size () const
                                     {
		return getMemberCount();
		}
}
namespace sttSav
{
  LZZ_INLINE int BinaryValue::GetInt () const
                                  {
		return GetInt32();
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetUint () const
                                        {
		return GetUint32();
		}
}
namespace sttSav
{
  LZZ_INLINE int32_t BinaryValue::GetInt32 () const
                                        {
		int32_t v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetUint32 () const
                                          {
		uint32_t v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE int64_t BinaryValue::GetInt64 () const
                                        {
		int64_t v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE uint64_t BinaryValue::GetUint64 () const
                                          {
		uint64_t v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE float BinaryValue::GetFloat () const
                                      {
		float v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE double BinaryValue::GetDouble () const
                                        {
		double v;
		dec->parseAt(payloadOffset(), v);
		return v;
		}
}
namespace sttSav
{
  LZZ_INLINE bool BinaryValue::GetBool () const
                                    {
		uint8_t v;
		dec->parseAt(payloadOffset(), v);
		return v != 0;
		}
}
namespace sttSav
{
  LZZ_INLINE uint32_t BinaryValue::GetStringLength () const
                                                {
		StringDecoder d(*dec);
		d.seek = payloadOffset();
		return (uint32_t)d.parseSize();
		}
}
namespace sttSav
{
  LZZ_INLINE BinaryWriter::BinaryWriter ()
    : enc (NULL)
                                          {}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::onValueWritten ()
                                     {
		if (!stack.empty() && !stack.back().isObject)
			stack.back().memberCount++;
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::startContainer (uint8_t const bvType, bool const isObject)
                                                                              {
		onValueWritten();

		scope s;
		s.startOffset = enc->getSeek();
		s.memberCount = 0;
		s.isObject = isObject;
		stack.push_back(s);

		enc->parse<uint8_t>(bvType);
		enc->parse<uint32_t>(0); // Jump placeholder
		enc->parse<uint32_t>(0); // Member count placeholder
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::endContainer ()
                                   {
		STTSAV_ASSERT(!stack.empty());

		const scope s = stack.back();
		stack.pop_back();

		const uint32_t jump = uint32_t(enc->getSeek() - s.startOffset);

		enc->parseAt<uint32_t>(s.startOffset + 1, jump);
		enc->parseAt<uint32_t>(s.startOffset + 5, s.memberCount);
		}
}
namespace sttSav
{
  template <typename T>
  LZZ_INLINE void BinaryWriter::writePrimitive (uint8_t const bvType, T const value)
                                                                        {
		onValueWritten();
		enc->parse<uint8_t>(bvType);
		enc->parse<T>(value);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::StartObject ()
                                  {
		startContainer(bvConstants::BV_OBJECT, true);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::StartArray ()
                                 {
		startContainer(bvConstants::BV_ARRAY, false);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::EndObject ()
                                {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(stack.back().isObject);
		endContainer();
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::EndArray ()
                               {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(!stack.back().isObject);
		endContainer();
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Key (char const * str)
                                         {
		STTSAV_ASSERT(!stack.empty());
		STTSAV_ASSERT(stack.back().isObject);
		stack.back().memberCount++;
		enc->parseString(str, strlen(str));
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int (int const v)
                                     { Int32(v); }
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int8 (int8_t const v)
                                         {
		writePrimitive<int8_t>(bvConstants::BV_INT8, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int16 (int16_t const v)
                                           {
		writePrimitive<int16_t>(bvConstants::BV_INT16, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int32 (int32_t const v)
                                           {
		writePrimitive<int32_t>(bvConstants::BV_INT32, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Int64 (int64_t const v)
                                           {
		writePrimitive<int64_t>(bvConstants::BV_INT64, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint (unsigned int const v)
                                           { Uint32(v); }
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint8 (uint8_t const v)
                                           {
		writePrimitive<uint8_t>(bvConstants::BV_UINT8, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint16 (uint16_t const v)
                                             {
		writePrimitive<uint16_t>(bvConstants::BV_UINT16, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint32 (uint32_t const v)
                                             {
		writePrimitive<uint32_t>(bvConstants::BV_UINT32, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Uint64 (uint64_t const v)
                                             {
		writePrimitive<uint64_t>(bvConstants::BV_UINT64, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Float (float const v)
                                         {
		writePrimitive<float>(bvConstants::BV_FLOAT, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Double (double const v)
                                           {
		writePrimitive<double>(bvConstants::BV_DOUBLE, v);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::Bool (bool const v)
                                       {
		writePrimitive<uint8_t>(bvConstants::BV_BOOL, v ? 1 : 0);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (char const * str, uint32_t const len)
                                                                {
		onValueWritten();
		enc->parse<uint8_t>(bvConstants::BV_STRING);
		enc->parseString(str, len);
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (char const * str)
                                            {
		return String(str, strlen(str));
		}
}
namespace sttSav
{
  LZZ_INLINE void BinaryWriter::String (STTSAV_STRING const & str)
                                                     {
		return String(str.data(), str.size());
		}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#define STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#define LZZ_OVERRIDE
// binaryValueWriter.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  STTSAV_STRING BinaryValue::GetString () const
                                        {
		STTSAV_STRING out;
		GetStringRef(out);
		return out;
		}
}
namespace sttSav
{
  void BinaryValue::GetStringRef (STTSAV_STRING & out) const
                                                    {
		StringDecoder d(*dec);
		d.seek = payloadOffset();
		d.parseString(out);
		}
}
namespace sttSav
{
  BinaryValue BinaryValue::operator [] (uint32_t index)
                                               {
		STTSAV_ASSERT(IsArray());
		STTSAV_ASSERT(index < Size());

		uint64_t off = childOffset();

		for (uint32_t i = 0; i < index; ++i) {
			BinaryValue v;
			v.dec = dec;
			v.offset = off;
			off = v.nextOffset();
			}

		BinaryValue out;
		out.dec = dec;
		out.offset = off;
		return out;
		}
}
namespace sttSav
{
  BinaryValue BinaryValue::operator [] (char const * key)
                                                {
		STTSAV_ASSERT(IsObject());
		
		uint64_t off = childOffset();
		for (uint32_t i = 0; i < Size(); ++i) {
			StringDecoder d(*dec);
			d.seek = off;
			
			STTSAV_STRING name;
			d.parseString(name);

			if (name == key) {
				BinaryValue out;
				out.dec = dec;
				out.offset = d.seek;
				return out;
				}
			
			BinaryValue v;
			v.dec = dec;
			v.offset = d.seek;
			off = v.nextOffset();
			}
		return BinaryValue();
		}
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_binaryValueWriter
#endif //STT_SAV_IMPL_IMPL
