// This file is autogenerated. See look at the .lzz files in the src/ directory for a more human-friendly version
#ifndef LZZ_OVERRIDE
	#define LZZ_OVERRIDE override
#endif
// XYArchiveDictionary.hh
//

#ifndef LZZ_XYArchiveDictionary_hh
#define LZZ_XYArchiveDictionary_hh
namespace sttSav {
	
struct XYDictConstants {
	constexpr static uint8_t NODE_TYPE_UNKNOWN = 0;
	constexpr static uint8_t NODE_TYPE_ROOT = 1;
	constexpr static uint8_t NODE_TYPE_LEAF = 2;

	static const char* nodeTypeToString(const uint8_t nt) {
		switch (nt) {
			case NODE_TYPE_ROOT: return "ROOT";
			case NODE_TYPE_LEAF: return "LEAF";
			default: return "(unknown)";
			}
		}
	};
	
} // namespace sttSav

#define LZZ_INLINE inline
namespace sttSav
{
  class XYArchiveDictionary : public ArchiveDictionaryI
  {
  public:
    struct unpackedKey
    {
      int16_t x;
      int16_t y;
      unpackedKey ();
      unpackedKey (int16_t _x, int16_t _y);
      unpackedKey (archiveKey key);
      archiveKey buildKey () const;
    };
    struct node
    {
      archiveId aid;
      int16_t x;
      int16_t y;
      uint32_t size;
      uint8_t type;
      node * parent;
      STTSAV_VECTOR <node*> children;
      node ();
      ~ node ();
      void destroyChildren ();
      void encode (BinaryWriter & w) const;
      void decode (BinaryValue const & val);
      bool containsExact (unpackedKey const & k) const;
      bool isRemainder () const;
      bool isAllowedToMerge () const;
      void dumpNode (int const depth) const;
    };
    DictionaryLookup <node, unpackedKey> mLookup;
    node root;
    XYArchiveDictionary ();
    ~ XYArchiveDictionary ();
    void initNewDictionary ();
    char const * getDictionaryName () const;
    archiveKey buildKey (int16_t const x, int16_t const y) const;
    archiveId getArchiveId (archiveKey const key) const;
    bool archiveContains (archiveId const aid, archiveKey const key) const;
    archiveId getArchiveIdFromShortlist (archiveKey const key, splitResult const * resultsIn, uint32_t const numResults) const;
    uint32_t extractArchiveIds (archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut) const;
    uint32_t getArchiveCountUpperBound () const;
    STTSAV_STRING encodeDictionary () const;
    uint32_t decodeDictionary (STTSAV_STRING const & data);
    void getArchiveFilename (archiveId const id, char * nameOut, uint32_t & lenOut, uint32_t const maxLen) const;
    bool splitArchive (archiveId const id, STTSAV_VECTOR <recordInfo> const & records, uint32_t const maxArchiveSize, splitResult * resultsOut, uint32_t & numResultsOut, uint32_t const maxResultsOut);
    bool getMergeCandidates (archiveId const id, archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut) const;
    bool mergeArchives (archiveId const * archives, uint32_t const numArchives);
    void dbgDump () const;
  };
}
namespace sttSav
{
  LZZ_INLINE XYArchiveDictionary::unpackedKey::unpackedKey ()
    : x (0), y (0)
                                                  {}
}
namespace sttSav
{
  LZZ_INLINE XYArchiveDictionary::unpackedKey::unpackedKey (int16_t _x, int16_t _y)
    : x (_x), y (_y)
                                                                          {}
}
namespace sttSav
{
  LZZ_INLINE XYArchiveDictionary::unpackedKey::unpackedKey (archiveKey key)
                                                   {
			x = int16_t(key.value & 0xffff);
			y = int16_t((key.value >> 16) & 0xffff);
			}
}
namespace sttSav
{
  LZZ_INLINE archiveKey XYArchiveDictionary::unpackedKey::buildKey () const
                                                   {
			archiveKey k;
			k.value = (uint32_t(uint16_t(x))) | (uint32_t(uint16_t(y)) << 16);
			return k;
			}
}
namespace sttSav
{
  LZZ_INLINE bool XYArchiveDictionary::node::isRemainder () const
                                                { return false; }
}
namespace sttSav
{
  LZZ_INLINE bool XYArchiveDictionary::node::isAllowedToMerge () const
                                                     {
			return parent && !(parent->type == XYDictConstants::NODE_TYPE_ROOT);
			}
}
#undef LZZ_INLINE
#endif
#undef LZZ_OVERRIDE

////////////////////////////////////////////////////////////////////////

#ifdef STT_SAV_IMPL
#ifndef STT_SAV_IMPL_DOUBLE_GUARD_XYArchiveDictionary
#define STT_SAV_IMPL_DOUBLE_GUARD_XYArchiveDictionary
#define LZZ_OVERRIDE
// XYArchiveDictionary.cpp
//

#define LZZ_INLINE inline
namespace sttSav
{
  XYArchiveDictionary::node::node ()
                        {
			aid.value = 0;
			x = 0; y = 0; size = 0;
			type = XYDictConstants::NODE_TYPE_UNKNOWN;
			parent = NULL;
			}
}
namespace sttSav
{
  XYArchiveDictionary::node::~ node ()
                         {
			destroyChildren();
			}
}
namespace sttSav
{
  void XYArchiveDictionary::node::destroyChildren ()
                                       {
			for (node* n : children)
				STTSAV_DEL(n, sizeof(node));
			children.clear();
			}
}
namespace sttSav
{
  void XYArchiveDictionary::node::encode (BinaryWriter & w) const
                                                   {
			w.StartObject();
			w.Key("aid");  w.Uint32(aid.value);
			w.Key("x");    w.Int16(x);
			w.Key("y");    w.Int16(y);
			w.Key("size"); w.Uint32(size);
			w.Key("type"); w.Uint8(type);
			
			w.Key("children");
			w.StartArray();
				for (node* c : children)
					c->encode(w);
			w.EndArray();
			w.EndObject();
			}
}
namespace sttSav
{
  void XYArchiveDictionary::node::decode (BinaryValue const & val)
                                                    {
			aid.value = val["aid"].GetUint32();
			x = val["x"].GetInt16();
			y = val["y"].GetInt16();
			size = val["size"].GetUint32();
			type = val["type"].GetUint8();

			parent = NULL;
			BinaryValue childArray = val["children"];

			STTSAV_ASSERT(childArray.IsArray());

			for (uint32_t i = 0; i < childArray.Size(); ++i) {
				node* c = STTSAV_NEW(node);
				c->decode(childArray[i]);
				c->parent = this;
				children.push_back(c);
				}
			}
}
namespace sttSav
{
  bool XYArchiveDictionary::node::containsExact (unpackedKey const & k) const
                                                               {
			// Returns true if this node contains this key exactly
			int32_t _x = x; // promote types
			int32_t _y = y;
			return k.x >= _x && k.x < _x + int32_t(size) && k.y >= _y && k.y < _y + int32_t(size);
			}
}
namespace sttSav
{
  void XYArchiveDictionary::node::dumpNode (int const depth) const
                                                     {
			#ifdef STTSAV_DBG
			for (int i = 0; i < depth; ++i)
				printf(" ");
			printf("type %s, id %i, x %i, y %i, sz %i\n", XYDictConstants::nodeTypeToString(type), (int)aid.value, (int) x, (int)y, (int)size);
			for (const node* const n : children)
				n->dumpNode(depth + 1);
			#endif
			}
}
namespace sttSav
{
  XYArchiveDictionary::XYArchiveDictionary ()
    : ArchiveDictionaryI ()
                                                     {
		root.type = XYDictConstants::NODE_TYPE_ROOT;
		}
}
namespace sttSav
{
  XYArchiveDictionary::~ XYArchiveDictionary ()
                               {}
}
namespace sttSav
{
  void XYArchiveDictionary::initNewDictionary ()
                                 {
		// creates an initial node for a new dictionary
		node* n = STTSAV_NEW(node);
		// top level 
		n->aid = mLookup.getNextId();
		n->type = XYDictConstants::NODE_TYPE_LEAF;
		n->x = -32768;
		n->y = -32768;
		n->size = 65536;
		n->parent = &root;
		root.children.push_back(n);
		mLookup.insertLookup(n);
		isInitialised = true;
		}
}
namespace sttSav
{
  char const * XYArchiveDictionary::getDictionaryName () const
                                              { return "XYArchiveDictionary"; }
}
namespace sttSav
{
  archiveKey XYArchiveDictionary::buildKey (int16_t const x, int16_t const y) const
                                                                    {
		return unpackedKey(x, y).buildKey();
		}
}
namespace sttSav
{
  archiveId XYArchiveDictionary::getArchiveId (archiveKey const key) const
                                                           {
		return mLookup.getArchiveId(key, const_cast<node*>(&root));
		}
}
namespace sttSav
{
  bool XYArchiveDictionary::archiveContains (archiveId const aid, archiveKey const key) const
                                                                              {
		return mLookup.archiveContains(aid, key);
		}
}
namespace sttSav
{
  archiveId XYArchiveDictionary::getArchiveIdFromShortlist (archiveKey const key, splitResult const * resultsIn, uint32_t const numResults) const
                                                                                                                                 {
		return getArchiveIdFromShortlist_worker(key, resultsIn, numResults);
		}
}
namespace sttSav
{
  uint32_t XYArchiveDictionary::extractArchiveIds (archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut) const
                                                                                                                          {
		uint32_t workingCount = 0;
		mLookup.extractArchiveIdsWorker(workingCount, archivesOut, numArchivesOut, maxArchivesOut);
		return workingCount;
		}
}
namespace sttSav
{
  uint32_t XYArchiveDictionary::getArchiveCountUpperBound () const
                                                   { return mLookup.mLookup.size(); }
}
namespace sttSav
{
  STTSAV_STRING XYArchiveDictionary::encodeDictionary () const
                                               {
		STTSAV_STRING r;
		StringEncoder enc(r);
		BinaryWriter w(&enc);
		w.StartObject();
		w.Key("dictionaryType");
		w.String(getDictionaryName());
		w.Key("dictionary");
		root.encode(w);
		w.EndObject();
		return r;
		}
}
namespace sttSav
{
  uint32_t XYArchiveDictionary::decodeDictionary (STTSAV_STRING const & data)
                                                             {
		StringDecoder d(data);
		BinaryValue vv(&d);
		BinaryValue v = vv["dictionary"];
		root.destroyChildren();
		root.decode(v);
		uint32_t unused = 0;
		mLookup.rebuildLookupArray(&root);
		isInitialised = true;
		return extractArchiveIds(NULL, unused, 0);
		}
}
namespace sttSav
{
  void XYArchiveDictionary::getArchiveFilename (archiveId const id, char * nameOut, uint32_t & lenOut, uint32_t const maxLen) const
                                                                                                                  {
		node* n = mLookup.getNodeByArchiveId(id);
		switch (n->type) {
			case XYDictConstants::NODE_TYPE_LEAF: 
				lenOut = snprintf(nameOut, maxLen, "region-sz%i-x%i-y%i.sav", n->size, n->x, n->y);
				return;
			default:
				STTSAV_ASSERT(false);
			}
		}
}
namespace sttSav
{
  bool XYArchiveDictionary::splitArchive (archiveId const id, STTSAV_VECTOR <recordInfo> const & records, uint32_t const maxArchiveSize, splitResult * resultsOut, uint32_t & numResultsOut, uint32_t const maxResultsOut)
                                                                                                                                                                                                       {
		numResultsOut = 0;

		node* n = mLookup.getNodeByArchiveId(id);
		if (!n)
			return false;

		// Can't subdivide any further.
		if (n->size <= 1)
			return false;

		//////////////////////////////////////////////////////////////////////////
		// Build quadrant buckets
		//////////////////////////////////////////////////////////////////////////

		STTSAV_VECTOR<splitBucket> buckets;

		const uint16_t half = n->size >> 1;

		for (const recordInfo& r : records) {
			unpackedKey k(r.key);
			uint32_t bucket = 0;

			if (int32_t(k.x) >= int32_t(n->x) + half)
				bucket |= 1;
			if (int32_t(k.y) >= int32_t(n->y) + half)
				bucket |= 2;
			splitBucket::appendOrInsert(buckets, bucket, r.length);
			}

		// Already below the split threshold.
		uint32_t totalBytes = 0;
		for (const splitBucket& b : buckets)
			totalBytes += b.bytes;

		if (totalBytes <= maxArchiveSize)
			return false;

		//////////////////////////////////////////////////////////////////////////
		// Convert this archive into a routing node.
		//////////////////////////////////////////////////////////////////////////

		mLookup.clearLookup(n->aid);
		n->aid.value = 0;

		//////////////////////////////////////////////////////////////////////////
		// Create the four deterministic children.
		//////////////////////////////////////////////////////////////////////////

		for (uint32_t q = 0; q < 4; ++q) {
			node* child = STTSAV_NEW(node);

			child->parent = n;
			child->type = XYDictConstants::NODE_TYPE_LEAF;

			child->size = half;

			child->x = n->x;
			child->y = n->y;

			if (q & 1)
				child->x += half;

			if (q & 2)
				child->y += half;

			child->aid = mLookup.getNextId();
			mLookup.insertLookup(child);

			n->children.push_back(child);

			STTSAV_ASSERT(numResultsOut < maxResultsOut);

			resultsOut[numResultsOut].aid = child->aid;
			resultsOut[numResultsOut].size = 0;

			++numResultsOut;
			}

		//////////////////////////////////////////////////////////////////////////
		// Populate archive sizes.
		//////////////////////////////////////////////////////////////////////////

		for (const splitBucket& b : buckets) {
			STTSAV_ASSERT(b.value < 4);
			resultsOut[b.value].size = b.bytes;
			}

		return true;
		}
}
namespace sttSav
{
  bool XYArchiveDictionary::getMergeCandidates (archiveId const id, archiveId * archivesOut, uint32_t & numArchivesOut, uint32_t const maxArchivesOut) const
                                                                                                                                            {
		return DictionaryMergeHelper<node,unpackedKey>::getMergeCandidatesWorker(mLookup, id, archivesOut, numArchivesOut, maxArchivesOut);
		}
}
namespace sttSav
{
  bool XYArchiveDictionary::mergeArchives (archiveId const * archives, uint32_t const numArchives)
                                                                                  {
		return DictionaryMergeHelper<node,unpackedKey>::mergeArchivesWorker(mLookup, archives, numArchives);
		}
}
namespace sttSav
{
  void XYArchiveDictionary::dbgDump () const
                             { root.dumpNode(0); }
}
#undef LZZ_INLINE
#undef LZZ_OVERRIDE
#endif //STT_SAV_IMPL_DOUBLE_GUARD_XYArchiveDictionary
#endif //STT_SAV_IMPL_IMPL
